# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: winamd64/python:3.7

stages: 
  - build
  - release

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pwd
  - ls
  - pip install -r environment/requirements.txt 
  - pip install pyinstaller


build:
  stage: build
  rules: # Run this job when a tag is created manually
    - if: $CI_COMMIT_TAG  
  script:
    - pyinstaller --onefile --distpath "Pyinstaller/build"  --workpath  "Pyinstaller/" PythonTranslatorExcelAgMIP.py
  artifacts:
    paths: ["/Pyinstaller/build/PythonTranslatorExcelAgMIP"]

# release:
#   stage: release
#   rules: # Run this job when a tag is created manually
#     - if: $CI_COMMIT_TAG   
#   script:
#     - echo 'Exe release job'
#     - ls
#     - ls Pyinstaller/build/
    
  
#   dependencies: []
  
