!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 3 $
!> $Author: dsu $
!> $Date: 2012-12-10 03:46:07 +0100 (Mon, 10 Dec 2012) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/ddtds_1.F90 $
!---------------------------------------------------------------------
!********************************************************************!

real*8 function rhonew (rhoold,tdsnew,tdsold,tempnew,tempold,drho_dtds,drho_dt, &
                        nonlindens_heat,cdens1,cdens2,cdens3,cdens4)
 
implicit none

real*8, intent(in)         :: &
 rhoold, &
 tdsnew, &
 tdsold, &
 tempnew, &
 tempold, &
 drho_dtds, &
 drho_dt, &
 cdens1, &
 cdens2, &
 cdens3, &
 cdens4
 
real*8, parameter          :: &
 r0=0.0d0, &
 r1000=1.0d3, &
 rkelvin=273.15d0

logical, intent(in)        :: &
 nonlindens_heat 

real*8                     :: &
 ddens_temp, &
 temp1, &
 temp2

 
 if (nonlindens_heat) then 
!cprovi--------------------------------------------------------------------------------------------------------
!cprovi Constant for the density changes by temperature 
!cprovi See Yusa and Oishi (1989)
!cprovi--------------------------------------------------------------------------------------------------------
     temp1=tempold + rkelvin
     temp2=tempnew + rkelvin
     ddens_temp = cdens1+r1000*temp1*(cdens2+temp1*(cdens3-temp1*cdens4))          
     ddens_temp = cdens1+r1000*temp2*(cdens2+temp2*(cdens3-temp2*cdens4)) - ddens_temp
 else 
     ddens_temp = drho_dt*(tempnew - tempold)
 end if
 
rhonew = rhoold + drho_dtds*(tdsnew-tdsold) + ddens_temp 
 
return 
      
end function 