!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 453 $
!> $Author: dsu $
!> $Date: 2017-02-21 19:54:05 +0100 (Tue, 21 Feb 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/dratemin_salinity.F90 $
!---------------------------------------------------------------------
!********************************************************************!

    subroutine dratemin_salinity(totc,c, sar, sarinc, im, ivol)
    use chem
    use gen, only : idbg, rank, b_enable_output, ilog
    
#ifdef OPENMP
      use omp_lib 
#endif  
 
      implicit none
      
      integer :: im, ivol 
      integer :: tid, i, ic
      integer :: info_debug
      
      real*8 :: totc, c, ratem      
      real*8 :: prodrc, prodrcinc
      real*8 :: salinity, sar
      real*8 :: salinityinc, sarinc

      dimension c(*),totc(*)

      real*8, parameter :: r0 = 0.0d0, r1 = 1.0d0
      
      !This is not needed when interface is declared
      !external raoult
      
      
#ifdef OPENMP
      tid = omp_get_thread_num() + 1
#else
      tid = 1
#endif
      
    
!c Calculate the salinity dependent mineral reaction rate coefficient f_s
!c  modify the ratem

      if (salinity_dependent(im)) then
          salinity = 0.0
          salinityinc = 0.0
          do ic = 1, nc-1
              if (namec(ic) .ne. 'o2(aq)') then
                salinity = salinity + gfwc(ic)*totc(ic)
                salinityinc = salinityinc + gfwc(ic)*totcinc(ic,tid)
              end if
          end do
          
          if (sdtype(im) .eq. 'equation') then
              sar = 0.0d0
              sarinc = 0.0d0
              
              if (salinity .le. min_salinity(im)) then
                  sar = min_sar(im)
                  sarinc = min_sar(im)
              else if (salinity .ge. max_salinity(im)) then
                  sar = max_sar(im)
                  sarinc = max_sar(im)
              else
                  do i = 1, nfac(im)
                      sar = sar + sfac_sdmin(im,i)*(salinity**(i-1))
                      sarinc = sarinc + sfac_sdmin(im,i)*(salinityinc**(i-1))
                  end do
              end if 
          end if
          
          if ((sar .lt. 0.0 .or. sar .gt. 1.0) .or.  &
               (sarinc .lt. 0.0 .or. sarinc .gt. 1.0)) then
            
            if (rank == 0 .and. b_enable_output) then
                write(ilog,'(2a)') 'In file dratemin_salinity: error calculating salinity dependent factor of mineral  ',namem(im)
                write(ilog,'(a,e12.5)') 'The salinity = ',salinity
                write(ilog,'(a,e12.5)') 'The coefficient sar = ',sar
                write(ilog,'(a,e12.5)') 'The coefficient sarinc = ',sarinc
                write(ilog,*) 'It should be between 0.0 to less or equal 1.0.'
                stop
            end if
          end if
          
      end if 
      
#ifdef DEBUG
      info_debug = 0
      if (rank == 0 .and. b_enable_output .and. info_debug.gt.0 .and. (ivol .eq. 2 &
            .or. ivol .eq. 4 .or. ivol .eq. 8) .and. im .eq. 1) then
        write(ilog,'(a,i6)') 'ivol = ',ivol
        write(ilog,'(a,e12.5)') 'The salinity = ',salinity
        write(ilog,'(a,e12.5)') 'The coefficient sar = ',sar
        write(ilog,'(a,e12.5)') 'The coefficient ratem = ',ratem
      end if
      if (info_debug.eq.1) then
        !pause
      end if
#endif
      return
    
end subroutine

    