!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 453 $
!> $Author: dsu $
!> $Date: 2017-02-21 19:54:05 +0100 (Tue, 21 Feb 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/initsatw.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine initsatw
!c -------------------
!c
!c compute initial saturations 
!c
!c written by:      Uli Mayer - May 27, 96
!c
!c last modified:   Tom Henderson - March 18, 2005
!c
!c added calculation of reduced saturations for the 
!c presence of napl phase.  
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c 
!c                                                                    I O
!c passed:   -
!c
!c common: 
!c bbls.f    logical
!c           -------
!c           gas_bubbles         =.true. -> gas phase saturation is calculated      
!c                                below the water table
!c  
!c gen.f:    real*8:
!c           -------
!c           uvsnew(nn)         = solution vector (new time level)    + - 
!c           saold(nn)          = aqueous phase saturation            * +
!c                                - new time level
!c           sanew(nn)          = aqueous phase saturation            * +
!c                                - new time level
!c
!c           integer*4:
!c           ----------
!c           nn                 = total number of control volumes     + -
!c           mpropvs(nn)        = pointer array for allocation of     + -
!c                                material properties
!c
!c           logical:
!c           --------
!c           fully_saturated    = .true.  -> saturated conditions     + -
!c           variably_saturated = .true.  -> .not.fully_saturated,    + -
!c                                        -> variably saturated
!c                                           conditions
!c           mpropvs(nn)        = pointer array for allocation of     + -
!c                                material properties
!c
!c phys.f:   real*8:
!c           -------
!c           swr(nzn)           = residual saturation                 + -
!c           aentry(nzn)        = air entry pressure                  + -
!c           spalpha(nzn)       = soil hydraulic function parameter   + -
!c           spbeta(nzn)        = soil hydraulic function parameter   + -
!c           spgamma(nzn)       = soil hydraulic function parameter   + -
!c           aentry(nzn)        = air entry pressure                  + -
!c
!c dens.f:   integer*4:
!c           ----------
!c           ianpl(nnpl)        = pointer for napl components         * -
!c           inpl               = counter for napl components         * +
!c           nnpl               = total number of napl components     * -
!c
!c local:    real*8:
!c           -------
!c           r1                 = constant
!c           
!c           integer*4:
!c           ----------
!c           ivol               = counter (control volumes)
!c           izn                = pointer (material property) 
!c
!c external: satfpres  = compute saturation from pressure
!c ----------------------------------------------------------------------
 
      subroutine initsatw
 
      use parm
      use gen
      use phys
      use dens
      use bbls
#ifdef OPENMP
      use omp_lib 
#endif

      implicit none
      
      real*8 :: h, hm, swr1, xh_ovendry, satfpres
      
      integer :: i1, ivol, izn

      external satfpres, zero_r8_parallel, xh_ovendry

      real*8, parameter :: r0 = 0.0d0,r1 = 1.0d0, r100=100.0d0

!c  set tolerance level for napl saturation for calculation of 
!c  aqueous relative permeability

      napl_tol = 1.0d-10 ! defined real*8 in dens.f

!c calculate initial napl saturations

      call zero_r8_parallel(snnew,nngl,1,1)

      if (napl_permeability) then
#ifdef OPENMP
    !$omp parallel                                                    &
    !$omp if (nngl > numofloops_thred_initsatw_1)                     &
    !$omp num_threads(numofthreads_global)                            &
    !$omp default(shared)                                             &
    !$omp private (i1, inpl, ivol)                  
    !$omp do schedule(static)
#endif
        do ivol = 1,nngl             !loop over control volumes
          do inpl = 1, nnpl
            i1 = ianpl(inpl)
            snnew(ivol) = snnew(ivol) + phi(i1,ivol)/pornew(ivol)
          end do
          if (snnew(ivol) .lt. napl_tol) then
            snnew(ivol) = r0
          end if
        end do
#ifdef OPENMP
    !$omp end do
    !$omp end parallel
#endif 
      end if

!c fully saturated conditions
!c reduce initial aqueous phase saturations to account for the presence
!c of a napl phase

!c_trap initialize variable for bubble entrapment calculations
      unsaturated = .false.

      if (fully_saturated) then
#ifdef OPENMP
    !$omp parallel                                                    &
    !$omp if (nngl > numofloops_thred_initsatw_2)                     &
    !$omp num_threads(numofthreads_global)                            &
    !$omp default(shared)                                             &
    !$omp private (ivol)                  
    !$omp do schedule(static)
#endif
        do ivol=1,nngl
          sanew(ivol) = r1 - snnew(ivol)
          saold(ivol) = sanew(ivol)
          saold2(ivol) = sanew(ivol)
        end do
#ifdef OPENMP
    !$omp end do
    !$omp end parallel
#endif
!c  variably saturated conditions
!c  calculate saturations for each control volume from pressure and 
!c  residual napl saturation

      elseif (variably_saturated) then
#ifdef OPENMP
    !$omp parallel                                                    &
    !$omp if (nngl > numofloops_thred_initsatw_3)                     &
    !$omp num_threads(numofthreads_global)                            &
    !$omp default(shared)                                             &
    !$omp private (ivol, izn, h, hm, swr1)                  
    !$omp do schedule(static)
#endif
        do ivol=1,nngl
          izn = mpropvs(ivol)
          if (uvsnew(ivol).lt.aentry(izn)) then
!c_trap initialize variable for bubble entrapment calculations
            unsaturated(ivol) = .true.
            if (isovendrying(izn)) then
              h = uvsnew(ivol) * r100 / (ref_dens * gacc)
              hm = hm_ovendry(izn) * r100 / (ref_dens * gacc)
              swr1=xh_ovendry(h,r1,hm)*swr(izn)
            else
              swr1=swr(izn)
            end if
            sanew(ivol) = satfpres(swr1,aentry(izn),uvsnew(ivol),     & 
     &                             spalpha(izn),spbeta(izn),          &
     &                             spgamma(izn))

!c reduce water saturation by residual NAPL saturation

            sanew(ivol) = sanew(ivol) - snnew(ivol)
            sgnew(ivol) = r1-sanew(ivol) - snnew(ivol)
            sainc(ivol) = sanew(ivol)
          else
            if (gas_bubbles)then
              sanew(ivol) = r1 - snnew(ivol) - sgnew(ivol)
              sainc(ivol) = sanew(ivol)
            else
              sanew(ivol) = r1 - snnew(ivol)  
              sainc(ivol) = sanew(ivol)
            end if            
            
          end if
          saold(ivol) = sanew(ivol)
          saold2(ivol) = sanew(ivol)
          sgold(ivol) = sgnew(ivol)          

          if (trap_bubbles) then
            sa_app(ivol) = r1
            sa_min(ivol) = r1
            sa_min_old(ivol) = r1
            sgt(ivol) = r0
            sgt_old(ivol) = r0
            big_bubble(ivol) = .false.
            big_bub_old(ivol) = .false.
          end if
        
        end do
#ifdef OPENMP
    !$omp end do
    !$omp end parallel
#endif
      end if

!cbdg  do ivol = 1,nngl
!c      write(idbg, '(i5, es15.8)') ivol, sgnew(ivol)
!c      end do
!cdbg    stop

      return
      end
