!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 488 $
!> $Author: cblitz $
!> $Date: 2017-07-17 18:22:05 +0200 (Mon, 17 Jul 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/initpppm.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine initpppm
!c -------------------
!c
!c physical parameters for porous medium
!c
!c written by:      Uli Mayer - May 13, 96
!c
!c last modified:   Uli Mayer - November 25, 96
!c                  Sergi Molins - May 15, 2006
!c                                 read oil saturation from file
!c                                 account for decrease in porosity 
!c                                 according to oil sat
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   -
!c
!c common: 
!c parm.f:   -
!c
!c gen.f:    real*8:
!c           -------
!c           pornew(nn)         = porosity                            * +
!c           por_init(nn)       = initial porosity                    * +
!c           xg(nn)             = spatial coordinates in x-direction  + -
!c           yg(nn)             = spatial coordinates in y-direction  + -
!c           zg(nn)             = spatial coordinates in z-direction  + -
!c
!c           integer*4:
!c           ----------
!c           icnv               = unit number, data conversion and    + -
!c                                             temporary storage
!c           idat               = unit number, run specific input     + -
!c                                             file
!c           igen               = unit number, generic output file    + -
!c           ilog               = unit number, logbook                + -
!c           itmp               = unit number, temporary storage      + -
!c           l_zone_name        = length of zone name                 * +
!c           mpropvs(nn)        = pointer array for allocation of     * +
!c                                material properties
!c           nn                 = number of control volumes           + -
!c
!c           logical:
!c           --------
!c           reactive_transport = .true.  -> perform reactive         + -
!c                                           transport simulation
!c           varsat_flow        = .true.  -> perform flow simulation  + -
!c
!c           character:
!c           ----------
!c           section_header     = section header                      * +
!c           zone_name          = name of zone                        * +
!c
!c phys.f:   real*8:
!c           -------
!c           por                = porosity                            * +
!c
!c           integer*4:
!c           ----------
!c           mprop_name(nzn)    = name of material property zone      * +
!c           nzn                = number of material property zones   * +
!c
!c local:    real*8:
!c           -------
!c           r1                 = constant
!c           tiny               = small increment
!c           xpmin              = min. x-coordinate of property zone
!c           xpmax              = max. x-coordinate of property zone
!c           ypmin              = min. y-coordinate of property zone
!c           ypmax              = max. y-coordinate of property zone
!c           zpmin              = min. z-coordinate of property zone
!c           zpmax              = max. z-coordinate of property zone
!c
!c           integer*4:
!c           ----------
!c           izn                = counter (material property zones)
!c           ivol               = counter (control volumes)
!c           l_string           = length of text string
!c           nntemp             = counter (control volumes
!c                                possessing material properties)
!c
!c           logical:
!c           --------
!c           found_section      = .true.  -> section header was
!c                                           found in input file
!c           found_subsection   = .true.  -> subsection header was
!c                                           found in input file
!c
!c           character:
!c           ----------
!c           subsection         = name of subsection in input file
!c
!c external: findstrg  = find text string in file
!c           findzone  = find zone in input section
!c           mem_mat   = allocate memory for physical parameters 
!c                       in material property zones
!c           readbloc  = read section of input file and write to
!c                       temporary file
!c           readzone  = read zone in section of input file and 
!c                       write to temporary file
!c ----------------------------------------------------------------------
 
      subroutine initpppm
 
      use parm
      use gen
      use phys
      use file_unit, only : lun_get, lun_free
#ifdef OPENMP
      use omp_lib 
#endif
#ifdef PETSC
      use petsc_mpi_common, only : petsc_mpi_finalize
#endif
      
      implicit none
#ifdef PETSC_V3_6_X
#include <petsc/finclude/petscsys.h>
#elif PETSC
#include <finclude/petscsys.h>
#endif
      
      real*8 :: tauloc, rdummy, xpmin, xpmax, ypmin, ypmax, zpmin, zpmax
      
      integer :: i, ivol, izn, l_string, nntemp, igso

#ifdef PETSC
      integer :: nntemp_gbl
      PetscErrorCode :: ierrcode
#endif
     
      external findstrg, findzone, mem_mat, readbloc, readzone
      
      logical found_section, found_subsection
      character*72 subsection
      character*1 cdummy
      character*256 :: strbuffer
      real(8) :: marchieloc
      
      integer :: iskip, nskip

!MX      parameter (r1 = 1.0d0, tiny = 1.0d-5)
      real*8, parameter :: r1 = 1.0d0, tiny = 1.0d-6
    
!c  set default

      porosity_field = .false.
      tortuosity_field = .false.
      tauloc=r1
      marchieloc = r1
    
      if (varsat_flow.or.reactive_transport) then
    
!c  initialize number of control volumes with assigned material properties

        nntemp = 0

!c  read physical parameters for porous medium and write to temporary file
   
        section_header = 'physical parameters - porous medium'
        call readbloc (idat,itmp,section_header,found_section,.true.)
 
!c  define length of section header

        l_string = index(section_header,'  ')-1
        if (l_string.eq.-1.or.l_string.gt.72) then
           l_string=72
        end if

!c  terminate program if section header not found
        if (.not.found_section) then
          if (rank == 0) then  
            write(ilog,*) 'SIMULATION TERMINATED'
            write(ilog,*) 'error reading input file'
            write(ilog,*) 'section "',section_header(:l_string),    &
     &                    '" missing'
            close(ilog)
          end if
#ifdef PETSC
          call petsc_mpi_finalize
#endif
          stop
        end if

!c  write physical parameters for porous medium to generic output file
        if (b_enable_output .and. b_enable_output_gen) then
          write(igen,'(/72a)')('-',i=1,72)
          write(igen,'(a)') section_header(:l_string)
          write(igen,'(72a/)')('-',i=1,72)
        end if

!c  read number of material property zones

        read(itmp,*,err=991,end=991) nzn            !number of zones
    
!c  allocate memory for physical parameters in material property
!c  zones
 
        call mem_mat

!c  write number of material property zones to generic output file
        if (b_enable_output .and. b_enable_output_gen) then
          write(igen,'(a,i10)')                                     &
     &    'number of material property zones               = ',nzn
        end if

        do izn = 1,nzn

!c  read porosity field from file
          subsection = 'read porosity field from file'

          call findstrg(subsection,itmp,found_subsection)

          if (found_subsection) then
            open(ipor,file=prefix(:l_prfx)//'.por',status='unknown',  &
     &           form='formatted')
            
            porosity_field = .true.
    
!c  read porosities

            read(ipor,*,err=992,end=992) cdummy
            read(ipor,*,err=992,end=992) cdummy
            read(ipor,*,err=992,end=992) cdummy
            nskip = 0
            do ivol = 1,nngl
#ifdef PETSC
              do iskip = 1, node_idx_lg2g(ivol) - nskip -1  
                  read(ipor,*,end=992,err=992) rdummy
              end do
              nskip = node_idx_lg2g(ivol)
#endif
              read(ipor,*,err=992,end=992) rdummy, rdummy,rdummy,     &
     &                                     por_init(ivol)
            end do
        
            close(ipor)
            call lun_free(ipor)
                
          end if
        
!c  read tortuosity field from file

          subsection = 'read tortuosity field from file'

          call findstrg(subsection,itmp,found_subsection)

          if (found_subsection) then
             open(itor,file=prefix(:l_prfx)//'.tor',status='unknown', &
     &            form='formatted')
            
            tortuosity_field = .true.
    
!c  read tortuosities

            read(itor,*,err=993,end=993) cdummy
            read(itor,*,err=993,end=993) cdummy
            read(itor,*,err=993,end=993) cdummy
            nskip = 0
            do ivol = 1,nngl
#ifdef PETSC
              do iskip = 1, node_idx_lg2g(ivol) - nskip -1  
                  read(itor,*,end=993,err=993) rdummy
              end do
              nskip = node_idx_lg2g(ivol)
#endif
              read(itor,*,err=993,end=993) rdummy, rdummy,rdummy,     &
     &                                     tau(ivol)
            end do
        
            close(itor)
            call lun_free(itor)
                
        end if


!c  read physical parameters for porous medium

          subsection = 'number and name of zone'

          call findzone(subsection,itmp,found_subsection,izn,         &
     &                  zone_name)

          if (found_subsection) then

            call readzone(itmp,icnv,ilog,zone_name,found_subsection)

          else
            if (rank == 0) then
              write(ilog,*) 'SIMULATION TERMINATED'
              write(ilog,*) 'error in input file'
              write(ilog,*) 'section "',section_header(:l_string),'"'
              write(ilog,*) 'zone number "',izn, '" missing'
              close(ilog)
            end if
#ifdef PETSC
            call petsc_mpi_finalize
#endif
            stop

          end if

          mprop_name(izn) = zone_name

!c  define length of zone name

          l_zone_name = index(zone_name,'  ')-1
          if (l_zone_name.lt.0.or.l_zone_name.gt.72) then
            l_zone_name = 72
          end if

!c  read porosity from input file

        if (.not.porosity_field) then
        
          read(icnv,*,err=994,end=994) por
              
        end if
        
!c  read porosity from input file

        if (.not.tortuosity_field.and.assigned_tau) then
        
          read(icnv,*,err=994,end=994) tauloc
              
        end if
        
!c  read tortuosity update factor, alpha
        if (assign_marchies) then
            
            read(icnv,*,err=994,end=994) marchieloc
            
        end if

!c  read coordinates delineating zone

          subsection = 'extent of zone'

          call findstrg(subsection,icnv,found_subsection)

          if (found_subsection) then

            read(icnv,*,err=994,end=994) xpmin,xpmax,ypmin,ypmax, &
     &                                   zpmin,zpmax

          else
            if (rank == 0) then
              write(ilog,*) 'SIMULATION TERMINATED'
              write(ilog,*) 'error reading input file'
              write(ilog,*) 'section "',section_header(:l_string),'"'
              write(ilog,*) 'zone "', zone_name(:l_zone_name),'"'
              l_string = index(subsection,'  ')-1
              if (l_string.eq.-1.or.l_string.gt.72) then
                 l_string=72
              end if
              write(ilog,*) 'subsection "',subsection(:l_string),   &
     &                      '" missing'
              close(ilog)
            end if
#ifdef PETSC
            call petsc_mpi_finalize
#endif
            stop

          end if

!c  define extent of zone

          xpmin = xpmin-tiny
          xpmax = xpmax+tiny
          ypmin = ypmin-tiny
          ypmax = ypmax+tiny
          zpmin = zpmin-tiny
          zpmax = zpmax+tiny


! CBF c calculate and store zone volume in array to calculate evaporation and transpiration flux

          pvol(izn)=(xpmax-xpmin)*(ypmax-xpmin)*(zpmax-zpmin)	!CBF

 
!c  assign physical parameters to global system
#ifdef OPENMP
    !$omp parallel                                                    &
    !$omp if (nngl > numofloops_thred_initpppm_1)                     &
    !$omp num_threads(numofthreads_global)                            &
    !$omp default(shared)                                             &
    !$omp private(ivol)                                               &
    !$omp reduction(+:nntemp)
    !$omp do schedule(static)
#endif
          do ivol = 1,nngl                  !loop over control volumes

            if ((xg(ivol).gt.xpmin).and.(xg(ivol).lt.xpmax)) then
              if ((yg(ivol).gt.ypmin).and.(yg(ivol).lt.ypmax)) then
                if ((zg(ivol).gt.zpmin).and.(zg(ivol).lt.zpmax)) then

                  if (porosity_field) then
                      pornew(ivol) = por_init(ivol) 
                      porold(ivol) = por_init(ivol) 
                  else
                      pornew(ivol) = por    
                      por_init(ivol) = por
                      porold(ivol) = por
                      if (assigned_tau.and..not.tortuosity_field) then
                       tau(ivol) = tauloc
                      end if
                  end if
                  
                  if (assign_marchies) then
                      marchies(ivol) = marchieloc
                  end if
                  
#ifdef PETSC
                  if(node_idx_lg2l(ivol) > 0) then
                    nntemp = nntemp+1
                  end if
#else
                  nntemp = nntemp+1
#endif
                  mpropvs(ivol) = izn     !allocate material properties

                end if
              end if
            end if
          end do                          !loop over control volumes
#ifdef OPENMP
    !$omp end do
    !$omp end parallel
#endif 

          if (b_enable_output .and. b_enable_output_gen) then
            if (nzn.lt.10) then
              write(igen,'(/a,i1,a,1x,a)') 'material property zone ',  &
     &                                      izn,':',                   &
     &                                      zone_name(:l_zone_name)
            else
              write(igen,'(/a,i2,a,1x,a)') 'material property zone ',  &
     &                                      izn,':',                   &
     &                                      zone_name(:l_zone_name)
            end if
            write(igen,'(72a)')('-',i=1,72)
            write(igen,'(a,1pe10.3)')                                  &
     &      'porosity                                        = ', por
            if (assigned_tau) then  
              write(igen,'(a,1pe10.3)')                                &
     &      'tortuosity                                      = ', tauloc
              if (tauloc .gt. 1.0) then
                write(igen,'(2a)')                                     &
     &          '!!! Warning: tortuosity is greater than 1.0 in zone:',&
     &          zone_name(:l_zone_name)
              end if
            end if
            if (assign_marchies) then
               write(igen,'(a,1pe10.3)')                               &
     &      'tortuosity update factor, alpha                 = ', marchieloc 
            end if
          end if
        end do                     !loop over property zones

!c  check if material properties have been assigned correctly
#ifdef PETSC
        call MPI_Allreduce(nntemp, nntemp_gbl,1,MPI_INTEGER4,MPI_SUM,  &
                           Petsc_Comm_World,ierrcode)
        CHKERRQ(ierrcode)
        nntemp = nntemp_gbl
#endif

        if (nntemp.gt.nngbl) then

          if (rank == 0) then  
            write(ilog,*)
            write(ilog,'(a)')  &                 !screen or logbook
     &            'warning ...........'
            write(ilog,'(a,i6,a)')                                      &
     &            'porous medium properties have been assigned to  ',   &
     &             nntemp,' control volumes'
            write(ilog,'(a,i6)')                                        &
     &            'the actual number of control volumes is only',nngbl
            write(ilog,'(/72a)')('-',i=1,72)
          end if

        elseif (nntemp.lt.nngbl) then
            
          if (rank == 0) then
            write(ilog,*) 'could assign material properties only to ',  &
     &                  nntemp, ' control volumes'
            write(ilog,*) 'the actual number of control volumes is ',nngbl
            write(ilog,*) 'please check the material properties zone'
          end if

          goto 999

        end if                             !(nntemp.....)
        
!c ----- added: oil saturation
!c  read oil saturation field from file

        subsection = 'read oil saturation field from file'
        oil_saturation = .false.
        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
	      oil_saturation = .true.
          if(rank == 0 .and. b_enable_output) then
		    write(ilog,*) 'reading oil saturation field from file'
            write(ilog,'(/72a)')('-',i=1,72)
          end if
	      igso = lun_get()

	      open(igso,file=prefix(:l_prfx)//'.gso',status='unknown',     &
               form='formatted')

!c  read oil saturation
          read(igso,*,err=995,end=995) cdummy
	      read(igso,*,err=995,end=995) cdummy
	      read(igso,*,err=995,end=995) cdummy
          nskip = 0
          do ivol = 1,nngl
            
#ifdef PETSC
            do iskip = 1, node_idx_lg2g(ivol) - nskip -1  
              read(igso,*,end=999,err=999) rdummy
            end do
            nskip = node_idx_lg2g(ivol)
#endif
            read(igso,*,err=995,end=995) rdummy, rdummy, rdummy,       &
                                         sonew(ivol)
          end do

		  close (igso)
          call lun_free(igso)

!c  account for decreased porosity due to presence of oil
          do ivol = 1,nngl
            pornew(ivol) = pornew(ivol) - sonew(ivol) * pornew(ivol)
            porold(ivol) = pornew(ivol)
	      enddo
			    
	    end if

!c ----- end oil saturation
!c ----- added: read porosity
!c  read oil saturation field from file

        subsection = 'read So field from file - no feedback on sat'
        call findstrg(subsection,itmp,found_subsection)

        if (found_subsection) then
          if (rank == 0 .and. b_enable_output) then  
	        write(ilog,*)                                              &
                  'reading So field from file - no feedback on sat'
          end if
	      igso = lun_get()
	      open(igso,file=prefix(:l_prfx)//'.gso',status='unknown',     &
               form='formatted')

!c  read oil saturation

          read(igso,*,err=995,end=995) cdummy
	      read(igso,*,err=995,end=995) cdummy
	      read(igso,*,err=995,end=995) cdummy
          nskip = 0
          do ivol = 1,nngl            
#ifdef PETSC
            do iskip = 1, node_idx_lg2g(ivol) - nskip -1  
              read(igso,*,end=999,err=999) rdummy
            end do
            nskip = node_idx_lg2g(ivol)
#endif
            read(igso,*,err=995,end=995) rdummy, rdummy, rdummy,       &
                                         sonew(ivol)
          end do

		  close (igso)
          call lun_free(igso)

!c  account for decreased porosity due to presence of oil
	      do ivol=1,nngl
            pornew(ivol) = pornew(ivol) - sonew(ivol) * pornew(ivol)
            porold(ivol) = pornew(ivol)
	      enddo
			    
	    end if

!c ----- end read porosity

!c  set porosity por = 1 for batch problems

      else

        por = r1
 
      end if

      goto 1000

991   continue
      backspace(itmp)
      read(itmp,'(a)') strbuffer
      if (rank == 0) then
        write(ilog,*) 'SIMULATION TERMINATED'
        write(ilog,'(2a)') 'error reading in itemp data: ',trim(strbuffer)
        write(*,*) 'SIMULATION TERMINATED'
        write(*,'(2a)') 'error reading in itemp data: ',trim(strbuffer)
        close(ilog)
      end if
#ifdef PETSC
      call petsc_mpi_finalize
#endif
      stop

992   continue
      backspace(ipor)
      read(ipor,'(a)') strbuffer
      if (rank == 0) then
        write(ilog,*) 'SIMULATION TERMINATED'
        write(ilog,'(2a)') 'error reading in ipor data: ',trim(strbuffer)
        write(*,*) 'SIMULATION TERMINATED'
        write(*,'(2a)') 'error reading in ipor data: ',trim(strbuffer)
        close(ilog)
      end if
#ifdef PETSC
      call petsc_mpi_finalize
#endif
      stop

993   continue
      backspace(itor)
      read(itor,'(a)') strbuffer
      if (rank == 0) then
        write(ilog,*) 'SIMULATION TERMINATED'
        write(ilog,'(2a)') 'error reading in itor data: ',trim(strbuffer)
        write(*,*) 'SIMULATION TERMINATED'
        write(*,'(2a)') 'error reading in itor data: ',trim(strbuffer)
        close(ilog)
      end if
#ifdef PETSC
      call petsc_mpi_finalize
#endif
      stop

994   continue
      backspace(icnv)
      read(icnv,'(a)') strbuffer
      if (rank == 0) then
        write(ilog,*) 'SIMULATION TERMINATED'
        write(ilog,'(2a)') 'error reading in icnv data: ',trim(strbuffer)
        write(*,*) 'SIMULATION TERMINATED'
        write(*,'(2a)') 'error reading in icnv data: ',trim(strbuffer)
        close(ilog)
      end if
#ifdef PETSC
      call petsc_mpi_finalize
#endif
      stop
      
995   continue
      backspace(igso)
      read(igso,'(a)') strbuffer
      if (rank == 0) then
        write(ilog,*) 'SIMULATION TERMINATED'
        write(ilog,'(2a)') 'error reading nodal oil saturation data: ',&
                           trim(strbuffer)
        write(*,*) 'SIMULATION TERMINATED'
        write(*,'(2a)') 'error reading nodal oil saturation data: ',   &
                         trim(strbuffer)
        close(ilog)
      end if
#ifdef PETSC
      call petsc_mpi_finalize
#endif
      stop

999   continue
      if (rank == 0) then
        write(ilog,*) 'SIMULATION TERMINATED'
        write(ilog,*) 'error reading input file'
        write(ilog,*) 'section "',section_header(:l_string),'"'
        close(ilog)
      end if
#ifdef PETSC
      call petsc_mpi_finalize
#endif
      stop


1000  return
      end
