!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 453 $
!> $Author: dsu $
!> $Date: 2017-02-21 19:54:05 +0100 (Tue, 21 Feb 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/initicvs.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine initicvs
!c -------------------
!c
!c initial condition (variably saturated flow)
!c
!c written by:      Uli Mayer - May 17, 96
!c
!c last modified:   Uli Mayer - November 25, 96
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c 
!c                                                                    I O
!c passed:   -
!c
!c common:   
!c gen.f:    real*8:
!c           -------
!c           hhead(nn)          = hydraulic head                      * +
!c           uvsnew(nn)         = solution vector (new time level)    * +
!c           uvsold(nn)         = solution vector (old time level)    * +
!c           sgnew(nn)          = gaseous phase saturation 
!c                                (new time level)
!c           integer*4:
!c           ----------
!c           icnv               = unit number, data conversion and    + -
!c                                             temporary storage
!c           idat               = unit number, run specific input     + -
!c                                             file
!c           idbg               = unit number, debugging file         + -
!c           igen               = unit number, generic output file    + -
!c           ilog               = unit number, logbook                + -
!c           itmp               = unit number, temporary storage      + -
!c           l_prfx             = length of prefix of I/O files       + -
!c           l_zone_name        = length of zone name                 + -
!c           nn                 = total number of control volumes     + -
!c
!c           logical:
!c           --------
!c           fully_saturated    = .true.  -> saturated conditions     + -
!c           hydraulic_head     = .true.  -> initial condition in     + -
!c                                           terms of hydraulic head
!c           pressure_head      = .true.  -> initial condition in     + -
!c                                           terms of pressure head
!c           variably_saturated = .true.  -> .not.fully_saturated,    + -
!c                                        -> variably saturated
!c                                           conditions
!c
!c           character:
!c           ----------
!c           prefix             = prefix name for all I/O files       + -
!c           section_header     = section header                      + -
!c           zone_name          = name of zone                        * +
!c
!c local:    real*8:
!c           -------
!c           hinitial           = initial condition for zone 
!c           rdummy             = real*8 dummy variable
!c           tiny               = small increment
!c           ximin              = min. limit of zone in 
!c                                x-direction
!c           ximax              = max. limit of zone in 
!c                                x-direction
!c           yimin              = min. limit of zone in 
!c                                y-direction
!c           yimax              = max. limit of zone in 
!c                                y-direction
!c           zimin              = min. limit of zone in 
!c                                z-direction
!c           zimax              = max. limit of zone in 
!c                                z-direction
!c           sginitial          = initial gas saturation read from file
!c
!c
!c           integer*4:
!c           ----------
!c           icvs               = unit number - initial condition 
!c                                              for variably 
!c                                              saturated flow
!c           iiz                = counter (zones)
!c           ivol               = counter (control volumes)
!c           l_string           = length of text string
!c           niz                = number of zones           
!c
!c           logical:
!c           --------
!c           found_section      = .true.  -> section header was
!c                                           found in input file
!c           found_subsection   = .true.  -> subsection header was
!c                                           found in input file
!c           initcond_file      = .true.  -> read initial condition 
!c                                           from file
!c
!c           character:
!c           ----------
!c           cdummy             = character dummy variable
!c           subsection         = name of subsection in input file
!c
!c external: findstrg  = find text string in file 
!c           findzone  = find zone in input section
!c           readbloc  = read section of input file and write to
!c                       temporary file
!c           readzone  = read zone in section of input file and 
!c                       write to temporary file
!c ----------------------------------------------------------------------
 
      subroutine initicvs
 
      use parm
      use gen
      use file_unit, only : lun_get, lun_free
#ifdef OPENMP
      use omp_lib 
#endif
#ifdef PETSC
      use petsc_mpi_common, only : petsc_mpi_finalize
#endif

      implicit none
      integer :: iskip, nskip
      integer :: i, i1, icvs, ivol, iiz, l_string, niz
      real*8 :: rdummy, theta_a, theta_g, hinitial, ximin, ximax,      &
                yimin, yimax, zimin, zimax, sginitial

      external findstrg, findzone, readbloc, readzone

      logical found_section, found_subsection, initcond_file,          &
              gassat_initial
      character*1 cdummy
      character*72 subsection

      real*8, parameter :: r0=0.0d0, tiny = 1.d-10
      
      sanew = r0
      sgnew = r0
      sginitial = r0

      if(rank == 0 .and. b_enable_output) then
        write(*,*) 'initial condition - ',          &
     &             'variably saturated flow'
        write(*,*) ('-',i=1,72)
        write(*,*)
        write(ilog,'(2a)') 'initial condition - ',  &
     &                   'variably saturated flow'
        write(ilog,'(72a/)')('-',i=1,72)      
      end if
 
!c  read section header for initial condition of variably saturated
!c  flow simulation
   
      section_header = 'initial condition - variably saturated flow'
      call readbloc (idat,itmp,section_header,found_section,.true.)
 
!c  define length of section header

      l_string = index(section_header,'  ')-1
      if (l_string.eq.-1.or.l_string.gt.72) then
         l_string=72
      end if

!c  terminate program if section header not found

      if (.not.found_section) then
        if (rank == 0) then  
          write(ilog,*) 'SIMULATION TERMINATED'
          write(ilog,*) 'error reading input file'
          write(ilog,*) 'section "',section_header(:l_string),'" missing'
          close(ilog)
        end if
#ifdef PETSC
        call petsc_mpi_finalize
#endif
        stop
      end if

!c  write section header to generic output file  
      if (b_enable_output .and. b_enable_output_gen) then
        write(igen,'(/72a)')('-',i=1,72)
        write(igen,'(a)') section_header(:l_string)
        write(igen,'(72a/)')('-',i=1,72)
      end if

!c  define logical flag to determine if initial condition will be
!c  - read from file (steady state)
!c  - specified in input file

      subsection = 'read initial condition from file'

      call findstrg(subsection,itmp,found_subsection)

      if (found_subsection) then
        initcond_file = .true.
      else
        initcond_file = .false.
      end if
      

!c  read initial condition from file

      if (initcond_file) then
 
!c  open file containing initial condition
!c  *.gsp file format

        !icvs  = 13 
        icvs = lun_get()
        open(icvs,file=prefix(:l_prfx)//'.ivs',status='old',  &
     &            form='formatted')

        do i1 = 1,3
          read(icvs,*,err=998,end=998) cdummy       !skip header
        end do

        cdummy = cdummy    !get rid of stupid error messages

!c  for fully saturated flow

        if (fully_saturated) then
          nskip = 0  
          do ivol = 1,nngl
#ifdef PETSC
            do iskip = 1, node_idx_lg2g(ivol) - nskip -1  
                read(icvs,*,end=999,err=999) rdummy
            end do
            nskip = node_idx_lg2g(ivol)
#endif
            read(icvs,*,err=998,end=998) rdummy,rdummy,rdummy,    &
     &                                   uvsnew(ivol)
            uvsold(ivol) = uvsnew(ivol)
          end do

!c  for variably saturated flow

        elseif (variably_saturated) then
          nskip = 0  
          do ivol = 1,nngl
#ifdef PETSC
            do iskip = 1, node_idx_lg2g(ivol) - nskip -1  
                read(icvs,*,end=999,err=999) rdummy
            end do
            nskip = node_idx_lg2g(ivol)
#endif
            read(icvs,*,err=998,end=998) rdummy,rdummy,rdummy,    &
     &                                   hhead(ivol),uvsnew(ivol),& 
     &                                   sanew(ivol),theta_a,     &
     &                                   sgnew(ivol),theta_g
                 uvsold(ivol) = uvsnew(ivol)
                 saold(ivol) = sanew(ivol)
               sgold(ivol) = sgnew(ivol)
          end do
        end if   

        rdummy = rdummy     ! get rid of stupid error messages

!c  close file

        close(icvs)
        call lun_free(icvs)

!c  initial condition specified in input file

      else

!c  read number of zones for initial condition
 
        rewind(itmp)
        read(itmp,*,err=999,end=999) niz
        if (b_enable_output .and. b_enable_output_gen) then
          write(igen,'(a,i10)')                                 &
     &    'number of zones for initial condition           = ',niz
        end if
        
!c  read name of zone

        do iiz=1,niz                !loop over number of zones

          subsection = 'number and name of zone'

          call findzone(subsection,itmp,found_subsection,iiz, &
     &                  zone_name)

          if (found_subsection) then

            call readzone(itmp,icnv,ilog,zone_name,found_subsection)

          else
            if (rank == 0) then
              write(ilog,*) 'SIMULATION TERMINATED'
              write(ilog,*) 'error in input file'
              write(ilog,*) 'section "',section_header(:l_string),'"'
              write(ilog,*) 'zone number "',iiz, '" missing'
              close(ilog)
            end if
#ifdef PETSC
            call petsc_mpi_finalize
#endif
            stop

          end if

!c  define length of zone name

          l_zone_name = index(zone_name,'  ')-1
          if (l_zone_name.lt.0.or.l_zone_name.gt.72) then
            l_zone_name = 72
          end if

!c  read initial condition for current zone

          subsection = 'initial condition'

          call findstrg(subsection,icnv,found_subsection)

          if (found_subsection) then

            read(icnv,*,err=999,end=999) hinitial

          else
            if (rank == 0) then
              write(ilog,*) 'SIMULATION TERMINATED'
              write(ilog,*) 'error reading input file'
              write(ilog,*) 'section "',section_header(:l_string),'"'
              write(ilog,*) 'zone "', zone_name(:l_zone_name),'"'
              l_string = index(subsection,'  ')-1
              if (l_string.eq.-1.or.l_string.gt.72) then
                 l_string=72
              end if
              write(ilog,*) 'subsection "',subsection(:l_string),   &
     &                   '" missing'
              close(ilog)
            end if
            
#ifdef PETSC
            call petsc_mpi_finalize
#endif
            stop

          end if
          
!c_bubbles  read initial gas saturation for current zone
          gassat_initial = .false.

          subsection = 'initial gas saturation'

          call findstrg(subsection,icnv,found_subsection)

          if (found_subsection) then

            gassat_initial = .true.

            read(icnv,*,err=999,end=999) sginitial

          end if 

!c  read coordiantes delineating zone

          subsection = 'extent of zone'

          call findstrg(subsection,icnv,found_subsection)

          if (found_subsection) then

            read(icnv,*,err=999,end=999) ximin,ximax,yimin,yimax, &
     &                                   zimin,zimax

          else
            if (rank == 0) then
              write(ilog,*) 'SIMULATION TERMINATED'
              write(ilog,*) 'error reading input file'
              write(ilog,*) 'section "',section_header(:l_string),'"'
              write(ilog,*) 'zone "', zone_name(:l_zone_name),'"'
              l_string = index(subsection,'  ')-1
              if (l_string.eq.-1.or.l_string.gt.72) then
                 l_string=72
              end if
              write(ilog,*) 'subsection "',subsection(:l_string),   &
     &                   '" missing'
              close(ilog)
            end if
#ifdef PETSC
            call petsc_mpi_finalize
#endif
            stop
          end if

!c  increment coordinates delineating zone

          ximin = ximin-tiny
          ximax = ximax+tiny
          yimin = yimin-tiny
          yimax = yimax+tiny
          zimin = zimin-tiny
          zimax = zimax+tiny

!c  assign initial condition to global system

#ifdef OPENMP
    !$omp parallel                                                    &
    !$omp if (nngl > numofloops_thred_initicvs_1)                     &
    !$omp num_threads(numofthreads_global)                            &
    !$omp default(shared)                                             &
    !$omp private (ivol)                  
    !$omp do schedule(static)
#endif
          do ivol = 1,nngl

!c  check limits of boundary zone

            if ((xg(ivol).gt.ximin).and.(xg(ivol).lt.ximax)) then
              if ((yg(ivol).gt.yimin).and.(yg(ivol).lt.yimax)) then
                if ((zg(ivol).gt.zimin).and.(zg(ivol).lt.zimax)) then

                  if (pressure_head) then
                    hhead(ivol) = hinitial + zg(ivol)
                  elseif (hydraulic_head) then
                    hhead(ivol) = hinitial
                  end if
                  
!#ifdef DEBUG
!                  if(ivol == 14) then
!                      write(idbg,*) "-->initicvs hhead(ivol)", hhead(ivol)
!                  end if
!#endif

                  if (fully_saturated) then
                    uvsnew(ivol) = hhead(ivol)
                    uvsold(ivol) = hhead(ivol)
                  elseif (variably_saturated) then
                    uvsnew(ivol) = hhead(ivol)-zg(ivol)
                    uvsold(ivol) = hhead(ivol)-zg(ivol)
                  end if
!c_bubbles assign inital gas saturation to global system
                  if (gassat_initial.and.uvsnew(ivol).gt.r0) then
                    sgnew(ivol) = sginitial
                  end if
                end if      !(zg(ivol).gt.zimin).and.(zg(ivol).lt.zimax)
              end if        !(yg(ivol).gt.yimin).and.(yg(ivol).lt.yimax)
            end if          !(xg(ivol).gt.ximin).and.(xg(ivol).lt.ximax)
          end do
#ifdef OPENMP
    !$omp end do
    !$omp end parallel
#endif 
        end do              !end loop over zones

      end if                !initcond_file

!c  write output info to generic output file
      if (b_enable_output .and. b_enable_output_gen) then
        write(igen,'(/3a)') 'for detailed output see file ',    &
     &                       prefix(:l_prfx)//'_0.gsp'
      end if

      goto 1000

998   continue
      if (rank == 0) then
        write(ilog,*) 'SIMULATION TERMINATED'
        write(ilog,*) 'error reading initial condition for variably ',  &
     &                'saturated flow'
        write(ilog,*) 'file "',prefix(:l_prfx),'.ivs"'
        close(ilog)
      end if
#ifdef PETSC
      call petsc_mpi_finalize
#endif
      stop

999   continue
      if (rank == 0) then
        write(ilog,*) 'SIMULATION TERMINATED'
        write(ilog,*) 'error reading input file'
        write(ilog,*) 'section "',section_header(:l_string),'"'
        close(ilog)
      end if
#ifdef PETSC
      call petsc_mpi_finalize
#endif
      stop

1000  return
      end
