!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 453 $
!> $Author: dsu $
!> $Date: 2017-02-21 19:54:05 +0100 (Tue, 21 Feb 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/mem_naq.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c -----------------------------------------------------------------------
!c subroutine mem_naq
!c ------------------
!c
!c allocate memory for one-dimensional arrays of size naq and related 
!c arrays
!c
!c written by:      Uli Mayer - January 10, 2000
!c
!c last modified:   -
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   -
!c
!c common:
!c gen.f:    integer:
!c           --------
!c           ilog               = unit number, logbook file           + -
!c
!c chem.f:   real*8:
!c           -------
!c           eqaq(naq,nthreads) = equilibrium constants for           * +
!c                                intra-aqueous kinetic reactions
!c           eqaqs(naq)         = equilibrium constants for           * +
!c                                intra-aqueous kinetic reactions
!c                                at standard temperature
!c           dgaq(naq)          = activation energies for intra-      * +
!c                                aqueous kinetic reaction
!c           dhaq(naq)          = enthalpy changes for intra-aqueous  * +
!c                                kinetic reaction
!c           faqi(naq*nc)       = inhibition factors                  * +
!c           faqic(naq*nc)      = inhibition factors C^c              * +
!c           faqit(naq*nc)      = inhibition factors T^a              * +
!c           faqim(naq*nm)      = inhibition factors phi^m            * +
!c           faqhc(naq*nc)      = half saturation constants C^c       * +
!c           faqht(naq*nc)      = half saturation constants T^a       * +
!c           faqhm(naq*nm)      = half saturation constants phi^m     * +
!c           ordaqic(naq*nc)    = order of intra-aqueous kinetic      * +
!c                                reaction for inhibition terms C^c
!c           ordaqit(naq*nc)    = order of intra-aqueous kinetic      * +
!c                                reaction for inhibition terms T^a
!c           ordaqim(naq*nm)    = order of intra-aqueous kinetic      * +
!c                                reaction for inhibition terms phi^m
!c           ordaqhc(naq*nc)    = order of intra-aqueous kinetic      * +
!c                                reaction for hyerbolic terms C^c
!c           ordaqht(naq*nc)    = order of intra-aqueous kinetic      * +
!c                                reaction for hyerbolic terms T^a
!c           ordaqhm(naq*nm)    = order of intra-aqueous kinetic      * +
!c                                reaction for hyerbolic terms phi^m
!c           ordaqt(naq*nc)     = order of intra-aqueous kinetic      * +
!c                                reaction (T^a)
!c           ordaqc(naq*nc)     = order of intra-aqueous kinetic      * +
!c                                reaction (C^c)
!c           ordaqx(naq*nx)     = order of intra-aqueous kinetic      * +
!c                                reaction (C^x)
!c           rateaq(naq,nthreads)        
!c                              = reaction rates of intra-aqueous     * +
!c                                kinetic reaction
!c           ratecaq(naq,nthreads)
!c                              = log of rate constant for intra-     * +
!c                                aqueous kinetic reactions
!c                                (units: liter -  moles - seconds)
!c           ratecaqs(naq)      = log of rate constant for intra-     * +
!c                                aqueous kinetic reactions at
!c                                stndard temperature
!c                                (units: liter -  moles - seconds)
!c           sataq(naq,nthreads)= IAP/K for intra-aqueous kinetic     * +
!c                                reactions
!c           scalfac_aq(naq)    = scaling factors for intra-aqueous   * +
!c                                kinetic reactions
!c           xnuaq(naq*nc)      = stoichiometric coefficient of       * +
!c                                components in intra-aqueous
!c                                kinetic reaction
!c
!c           integer:
!c           --------
!c           iaaq(naq+1)        = row pointer array to                * +
!c                                stoichiometric coefficients in
!c                                intra-aqueous kinetic reactions
!c           iaaqi(2*naq+1)     = row pointer array to reactants      * +
!c                                in intra-aqueous kinetic reactions
!c                                (inhibition terms)
!c           iaaqic(naq+1)      = row pointer array to reactants      * +
!c                                in intra-aqueous kinetic reactions
!c                                (inhibition terms C^c)
!c           iaaqit(naq+1)      = row pointer array to reactants      * +
!c                                in intra-aqueous kinetic reactions
!c                                (inhibition terms T^a)
!c           iaaqim(naq+1)      = row pointer array to reactants      * +
!c                                in intra-aqueous kinetic reactions
!c                                (inhibition terms phi^m)
!c           iaaqhc(naq+1)      = row pointer array to reactants      * +
!c                                in intra-aqueous kinetic reactions
!c                                (hyperbolic terms C^c)
!c           iaaqht(naq+1)      = row pointer array to reactants      * +
!c                                in intra-aqueous kinetic reactions
!c                                (hyperbolic terms T^a)
!c           iaaqhm(naq+1)      = row pointer array to reactants      * +
!c                                in intra-aqueous kinetic reactions
!c                                (hyperbolic terms phi^m)
!c           iaaqt(naq+1)       = row pointer array to reactants      * +
!c                                in intra-aqueous kinetic reactions
!c                                (T^a)
!c           iaaqc(naq+1)       = row pointer array to reactants      * +
!c                                in intra-aqueous kinetic reactions
!c                                (C^c)
!c           iaaqx(naq+1)       = row pointer array to reactants      * +
!c                                in intra-aqueous kinetic reactions
!c                                (C^x)
!c           jaaq(naq*nc)       = column pointer array to             * +
!c                                stoichiometric coefficients in
!c                                intra-aqueous kinetic reactions
!c           jaaqi(naq*nc)      = column pointer array to reactants   * +
!c                                in intra-aqueous kinetic reactions
!c                                (inhibition terms)
!c           jaaqic(naq*nc)     = column pointer array to reactants   * +
!c                                in intra-aqueous kinetic reactions
!c                                (inhibition terms C^c)
!c           jaaqit(naq*nc)     = column pointer array to reactants   * +
!c                                in intra-aqueous kinetic reactions
!c                                (inhibition terms T^a)
!c           jaaqim(naq*nm)     = column pointer array to reactants   * +
!c                                in intra-aqueous kinetic reactions
!c                                (inhibition terms phi^m)
!c           jaaqhc(naq*nc)     = column pointer array to reactants   * +
!c                                in intra-aqueous kinetic reactions
!c                                (hyperbolic terms C^c)
!c           jaaqht(naq*nc)     = column pointer array to reactants   * +
!c                                in intra-aqueous kinetic reactions
!c                                (hyperbolic terms T^a)
!c           jaaqhm(naq*nm)     = column pointer array to reactants   * +
!c                                in intra-aqueous kinetic reactions
!c                                (hyperbolic terms phi^m)
!c           jaaqt(naq*nc)      = column pointer array to reactants   * +
!c                                in intra-aqueous kinetic reactions
!c                                (T^a)
!c           jaaqc(naq*nc)      = column pointer array to reactants   * +
!c                                in intra-aqueous kinetic reactions
!c                                (C^c)
!c           jaaqx(naq*nx)      = column pointer array to reactants   * +
!c                                in intra-aqueous kinetic reactions
!c                                (C^x)
!c           l_nameaq(naq)      = length of names of intra-aqueous    * +
!c                                kinetic reactions
!c           naq                = number of intra-aqueous kinetic     * +
!c                                reactions
!c           nc                 = number of components including h2o  + -
!c
!crevintaff
!c           logical:
!c           --------
!c           reverse_intra_affinity(naq) = .true. -> reverse affinity * +   
!c                                                   term if IAP/K > 1       
!crevintaff
!c
!c           character:
!c           ----------
!c           nameaq(naq)        = names of intra-aqueous kinetic      * +
!c                                reactions
!c           rtype_aq(naq)      = reaction type of intra-aqueouc      * +
!c                                kinetic reaction
!c                                'monod'
!c
!c local:    integer:
!c           --------
!c           ierr               = 0 -> memory allocation successful
!c
!c external: checkerr  = check for error during memory allocation
!c---------------------------------------------------------------------- 
!c WARNING
!c---------------------------------------------------------------------- 
!c All allocated variables are initialized to some value. This depends  
!c of its type:
!c 
!c real*8      => 0.0d0
!c integer     => 0 
!c character   => ' '    
!c logical     => .false. 
!c 
!c Sergio Andres Bea Jofre (2009)
!c
!c ----------------------------------------------------------------------
  
      subroutine mem_naq
 
      use parm
      use gen
      use chem
      
      implicit none
      
      integer :: ierr
 
      external checkerr

!c  main variables - intra-aqueous kinetic reactions

      allocate (eqaq(naq,nthreads), stat = ierr)
      eqaq=0.0d0
      call checkerr(ierr,'eqaq',ilog)

      allocate (eqaqs(naq), stat = ierr)
      eqaqs=0.0d0
      call checkerr(ierr,'eqaqs',ilog)

      allocate (dgaq(naq), stat = ierr)
      dgaq=0.0d0
      call checkerr(ierr,'dgaq',ilog)

      allocate (dhaq(naq), stat = ierr)
      dhaq=0.0d0
      call checkerr(ierr,'dhaq',ilog)

      allocate (faqhc(naq*nc), stat = ierr)
      faqhc=0.0d0
      call checkerr(ierr,'faqhc',ilog)

      allocate (faqht(naq*nc), stat = ierr)
      faqht=0.0d0
      call checkerr(ierr,'faqht',ilog)

      allocate (faqhm(naq*nm), stat = ierr)
      faqhm=0.0d0
      call checkerr(ierr,'faqhm',ilog)

      allocate (faqi(naq*nc), stat = ierr)
      faqi=0.0d0
      call checkerr(ierr,'faqi',ilog)

      allocate (faqic(naq*nc), stat = ierr)
      faqic=0.0d0
      call checkerr(ierr,'faqic',ilog)

      allocate (faqit(naq*nc), stat = ierr)
      faqit=0.0d0
      call checkerr(ierr,'faqit',ilog)

      allocate (faqim(naq*nm), stat = ierr)
      faqim=0.0d0
      call checkerr(ierr,'faqim',ilog)

      allocate (ordaqic(naq*nc), stat = ierr)
      ordaqic=0.0d0
      call checkerr(ierr,'ordaqic',ilog)

      allocate (ordaqit(naq*nc), stat = ierr)
      ordaqit=0.0d0
      call checkerr(ierr,'ordaqit',ilog)

      allocate (ordaqim(naq*nm), stat = ierr)
      ordaqim=0.0d0
      call checkerr(ierr,'ordaqim',ilog)

      allocate (ordaqhc(naq*nc), stat = ierr)
      ordaqhc=0.0d0
      call checkerr(ierr,'ordaqhc',ilog)

      allocate (ordaqht(naq*nc), stat = ierr)
      ordaqht=0.0d0
      call checkerr(ierr,'ordaqht',ilog)

      allocate (ordaqhm(naq*nm), stat = ierr)
      ordaqhm=0.0d0
      call checkerr(ierr,'ordaqhm',ilog)

      allocate (ordaqt(naq*nc), stat = ierr)
      ordaqt=0.0d0
      call checkerr(ierr,'ordaqt',ilog)

      allocate (ordaqc(naq*nc), stat = ierr)
      ordaqc=0.0d0
      call checkerr(ierr,'ordaqc',ilog)

      allocate (ordaqx(naq*nx), stat = ierr)
      ordaqx=0.0d0
      call checkerr(ierr,'ordaqx',ilog)

      allocate (rateaq(naq,nthreads), stat = ierr)
      rateaq=0.0d0
      call checkerr(ierr,'rateaq',ilog)

      allocate (ratecaq(naq,nthreads), stat = ierr)
      ratecaq=0.0d0
      call checkerr(ierr,'ratecaq',ilog)

      allocate (ratecaqs(naq), stat = ierr)
      ratecaqs=0.0d0
      call checkerr(ierr,'ratecaqs',ilog)

      allocate (sataq(naq,nthreads), stat = ierr)
      sataq=0.0d0
      call checkerr(ierr,'sataq',ilog)
      
!c_bubbles
      allocate (dg_limaq(naq), stat = ierr)
      dg_limaq=1.0d0
      call checkerr(ierr,'dg_limaq',ilog)      

      allocate (scalfac_aq(naq), stat = ierr)
      scalfac_aq=0.0d0
      call checkerr(ierr,'scalfac_aq',ilog)

      allocate (xnuaq(naq*nc), stat = ierr)
      xnuaq=0.0d0
      call checkerr(ierr,'xnuaq',ilog)

      allocate (iaaq(naq+1), stat = ierr)
      iaaq=0
      call checkerr(ierr,'iaaq',ilog)

      allocate (iaaqi(2*naq+1), stat = ierr)
      iaaqi=0 
      call checkerr(ierr,'iaaqi',ilog)

      allocate (iaaqic(naq+1), stat = ierr)
      iaaqic=0 
      call checkerr(ierr,'iaaqic',ilog)

      allocate (iaaqit(naq+1), stat = ierr)
      iaaqit= 0
      call checkerr(ierr,'iaaqit',ilog)

      allocate (iaaqim(naq+1), stat = ierr)
      iaaqim=0 
      call checkerr(ierr,'iaaqim',ilog)

      allocate (iaaqhc(naq+1), stat = ierr)
      iaaqhc=0 
      call checkerr(ierr,'iaaqhc',ilog)

      allocate (iaaqht(naq+1), stat = ierr)
      iaaqht=0 
      call checkerr(ierr,'iaaqht',ilog)

      allocate (iaaqhm(naq+1), stat = ierr)
      iaaqhm=0 
      call checkerr(ierr,'iaaqhm',ilog)

      allocate (iaaqc(naq+1), stat = ierr)
      iaaqc=0 
      call checkerr(ierr,'iaaqc',ilog)

      allocate (iaaqx(naq+1), stat = ierr)
      iaaqx=0 
      call checkerr(ierr,'iaaqx',ilog)

      allocate (iaaqt(naq+1), stat = ierr)
      iaaqt=0 
      call checkerr(ierr,'iaaqt',ilog)

      allocate (jaaq(naq*nc), stat = ierr)
      jaaq=0
      call checkerr(ierr,'jaaq',ilog)

      allocate (jaaqt(naq*nc), stat = ierr)
      jaaqt=0
      call checkerr(ierr,'jaaqt',ilog)

      allocate (jaaqc(naq*nc), stat = ierr)
      jaaqc=0
      call checkerr(ierr,'jaaqc',ilog)

      allocate (jaaqx(naq*nx), stat = ierr)
      jaaqx=0
      call checkerr(ierr,'jaaqx',ilog)

      allocate (jaaqhc(naq*nc), stat = ierr)
      jaaqhc=0
      call checkerr(ierr,'jaaqhc',ilog)

      allocate (jaaqht(naq*nc), stat = ierr)
      jaaqht=0
      call checkerr(ierr,'jaaqht',ilog)

      allocate (jaaqhm(naq*nm), stat = ierr)
      jaaqhm=0
      call checkerr(ierr,'jaaqhm',ilog)

      allocate (jaaqi(naq*nc), stat = ierr)
      jaaqi=0
      call checkerr(ierr,'jaaqi',ilog)

      allocate (jaaqic(naq*nc), stat = ierr)
      jaaqic=0
      call checkerr(ierr,'jaaqic',ilog)

      allocate (jaaqit(naq*nc), stat = ierr)
      jaaqit=0
      call checkerr(ierr,'jaaqit',ilog)

      allocate (jaaqim(naq*nm), stat = ierr)
      jaaqim=0
      call checkerr(ierr,'jaaqim',ilog)

      allocate (l_nameaq(naq), stat = ierr)
      l_nameaq=0 
      call checkerr(ierr,'l_nameaq',ilog)
      
!crevintaff
      allocate (reverse_intra_affinity(naq), stat = ierr)
      reverse_intra_affinity=.false.
      call checkerr(ierr,'reverse_intra_affinity',ilog)   
!crevintaff

      allocate (nameaq(naq), stat = ierr)
      nameaq='  '
      call checkerr(ierr,'nameaq',ilog)

      allocate (rtype_aq(naq), stat = ierr)
      rtype_aq=' ' 
      call checkerr(ierr,'rtype_aq',ilog)
      
!c isotopes
      allocate (iaaqhst(naq+1), stat = ierr)
      iaaqhst=0
      call checkerr(ierr,'iaaqhst',ilog)
            
      allocate (iaaqhst2(naq+1), stat = ierr)
      iaaqhst2=0
      call checkerr(ierr,'iaaqhst2',ilog)
            
      allocate (jaaqhst(naq*nc), stat = ierr)
      jaaqhst=0
      call checkerr(ierr,'jaaqhst',ilog)
            
      allocate (faqhst(naq*nc), stat = ierr)
      faqhst=0
      call checkerr(ierr,'faqhst',ilog)
            
      allocate (ordaqhst(naq*nc), stat = ierr)
      ordaqhst=0
      call checkerr(ierr,'ordaqhst',ilog)
            
      allocate (ntsca(naq*nc), stat = ierr)
      ntsca=0
      call checkerr(ierr,'ntsca',ilog)
            
      allocate (isotypea(naq*nc), stat = ierr)
      isotypea = ""
      call checkerr(ierr,'isotypea',ilog)
      
      allocate (isofraca(naq), stat = ierr)
      isofraca = .false.
      call checkerr(ierr,'isofraca',ilog)

      allocate (isofracam(naq), stat = ierr)
      isofracam = .false.
      call checkerr(ierr,'isofracam',ilog)

      allocate (nifra(naq), stat = ierr)
      nifra=0
      call checkerr(ierr,'nifra',ilog)      

      allocate (jamdalphaa(naq*nc), stat = ierr)
      jamdalphaa=0.0d0
      call checkerr(ierr,'jamdalphaa',ilog)      
      
      allocate (isoalphaa(naq), stat = ierr)
      isoalphaa=0
      call checkerr(ierr,'isoalphaa',ilog)      
      
      allocate (iamdisoa(naq+1), stat = ierr)
      iamdisoa=0
      call checkerr(ierr,'iamdisoa',ilog)      

      allocate (iamdisoa2(naq+1), stat = ierr)
      iamdisoa2=0
      call checkerr(ierr,'iamdisoa2',ilog)
            
      allocate (jamdisoa(naq*nc), stat = ierr)
      jamdisoa=0
      call checkerr(ierr,'jamdisoa',ilog)
      
      allocate (jamdisoa2(naq*nc), stat = ierr)
      jamdisoa2=0
      call checkerr(ierr,'jamdisoa2',ilog)
      
      return
      end
