!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 453 $
!> $Author: dsu $
!> $Date: 2017-02-21 19:54:05 +0100 (Tue, 21 Feb 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/mem_rt.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c -----------------------------------------------------------------------
!c subroutine mem_rt
!c -----------------
!c
!c allocate memory for reactive transport simulation
!c
!c written by:      Uli Mayer - Januray 6, 2000
!c
!c last modified:   Tom Henderson - June 1, 2006
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   -
!c
!c common:
!c bbls.f    real*8
!c           -------
!c           sanew_b(nn)          = water saturation prior to reactran and gasbub
!c                                    for convergence check of outer bubble loop
!c             c_update(nc,nn)      = component concentration at previous inner
!c                                    bubble iteration. 
!c gen.f:    real*8:
!c           -------
!c           c(nc,nngl)           = concentrations of free species      * +
!c                                - old time level [moles/l water]
!c           cnew(nc,nngl)        = concentrations of free species      * +
!c                                - new time level [moles/l water]
!c           cec_g(nngl)          = cation exchange capacity [meq/100g] * +
!c                                - global system
!c           cec_fraction_g(nsites_ion, nngl)                           * +
!c                              = cec fraction of multisite ion-
!c                                exchange sites - blobal system
!c           totcold(n,nngl)      = total aqueous component             * +
!c                                concentrations
!c                                - old time level [moles/l water]
!c           totcnew(n,nngl)      = total aqueous component             * +
!c                                concentrations
!c                                - new time level [moles/l water]
!c           totgold(nc,nngl)      = total gaseous component            * +
!c                                concentrations
!c                                - old time level [moles/l air]]
!c           totgnew(nc,nngl)      = total gaseous component            * +
!c                                concentrations
!c                                - new time level [moles/l air]
!c           totsold(n,nngl)      = total sorbed component              * +
!c                                concentrations
!c                                - old time level [moles/l bulk]
!c           totsold_ion(n,nngl)  = total sorbed component              * +
!c                                concentrations 
!c                                - old time level [moles/l bulk]
!c                                (ion-exchange)
!c           totsold_surf(n,nngl) = total sorbed component              * +
!c                                concentrations 
!c                                - old time level [moles/l bulk]
!c                                (surface-complex)
!c           totsnew(n,nngl)      = total sorbed component              * +
!c                                concentrations
!c                                - new time level [moles/l bulk]
!c           totsnew_ion(n,nngl)  = total sorbed component              * +
!c                                concentrations
!c                                - new time level [moles/l bulk]
!c                                (ion-exchange)
!c           totsnew_surf(n,nngl) = total sorbed component              * +
!c                                concentrations
!c                                - new time level [moles/l bulk]
!c                                (surface-complex)
!c           cmold(nm,nngl)       = mineral concentrations              * +
!c                                - old time level [moles/l bulk]
!c           cmnew(nm,nngl)       = mineral concentrations              * +
!c                                - new time level [moles/l bulk]
!c           gold(ng,nngl)        = gas concentrations                  * +
!c                                - old time level [moles/l air]
!c           gnew(ng,nngl)        = gas concentrations                  * +
!c                                - new time level [moles/l air]
!c           cx(nx,nngl)          = concentrations of secondary aqueous * +
!c                                species [moles/l water]
!c           gamma(nc+nx,nngl)    = activity coefficients of aqueous    * +
!c                                species [-]
!c           sionnew(nngl)        = ionic strength of solution          * +
!c           gammaold(nc+nx,nngl) = activity coefficients of aqueous    * +
!c                                species [-] - old time level
!c                                - new time level
!c           sionold(nngl)        = ionic strength of solution          * +
!c                                - old time level
!c           phi(nm,nngl)         = volume fractions of minerals        * +
!c           phiold(nm,nngl)      = volume fractions of minerals        * +
!c                                - old time level
!c           phi_init(nm,nngl)    = volume fractions of minerals        * +
!c                                - initial condition
!c           phinucthrd(nm,nngl) = volume fractions of mineral for     * +
!c                                nucleation threshold
!c                                - initial condition
!c           area(nm,nngl)        = mineral reactivity term             * +
!c                                (global system)
!c           area_init(nm,nngl)   = initial mineral reactivity term     * +
!c                                (global system)
!c           cflux(ncon,n)      = interfacial mass fluxes             * +
!c                                (aqueous phase)
!c           cstor(n)           = storage term (aqueous phase)        * +
!c           gflux(ncon,n)      = interfacial mass fluxes
!c                                (gaseous phase)
!c           gstor(n)           = storage term (gaseous phase)        * +
!c           dtotcflux(n)       = derivatives of total mass fluxes    * +
!c                                (aqueous phase)
!c           dtotgflux(n)       = derivatives of total mass fluxes    * +
!c                                (gaseous phase)
!c           ratemdp(nm,nngl)     = absolute dissolution-precipitation  * +
!c                                rates of minerals
!c           totcflux(n)        = total mass fluxes (aqueous phase)   * +
!c           totgflux(n)        = total mass fluxes (gaseous phase)   * +
!c           totmdp(n,nngl)       = total source/sink term towards      * +
!c                                total aqueous component
!c                                concentrations due to mineral
!c                                dissolution-precipitation reactions
!c           cfluxin(n)         = mass gain due to inflow in water    * +
!c                                phase in terms of total aqueous
!c                                component concentrations
!c           cfluxout(n)        = mass loss due to outflow in water   * +
!c                                phase in terms of total aqueous
!c                                component concentrations
!c           gfluxtbdy(ng)      = mass flux across top boundary       * +
!c                                (gaseous phase)
!c           gfluxin(n)         = mass gain due to inflow in air      * +
!c                                phase in terms of total gaseous
!c                                component concentrations
!c           gfluxout(n)        = mass loss due to outflow in air     * +
!c                                phase in terms of total gaseous
!c                                component concentrations
!c           cstordiff(n+nm)    = change in storage in terms of total * +
!c                                aqueous component concentrations
!c           gdegas(n)          = mass loss from aqueous phase due to * +
!c                                degassing                        
!c           gstordiff(n)       = change in storage in terms of total * +
!c                                gaseous component concentrations
!c           ordiff(n)          = global source-sink term due to      * +
!c                                oxidation/reduction reactions
!c           dpdiff(n+nm)       = source-sink term due to phase       * +
!c                                exchange with solid phase
!c                                (minerals)
!c           dpdiffp(ndr*nm)    = individual source-sink terms due    * +
!c                                to parallel dissolution-
!c                                precipitation reactions
!c           gdiff(n+ng)        = source-sink term due to phase       * +
!c                                exchange with air phase
!c           amass(n)           = total adsorbed mass                 * +
!c                                non-competitive sorption [moles]
!c           tmass(n)           = total mass in aqueous and gaseous   * +
!c                                phase in terms of total
!c                                component concentrations [moles]
!c           cmass(n)           = total mass in aqueous phase in      * +
!c                                terms of total aqueous component
!c                                concentrations [moles]
!c           gmass(ng)          = total mass in gaseous phase in      * +
!c                                terms of total gaseous component
!c                                concentrations [moles]
!c           cmmass(nm)         = total mineral mass in system        * +
!c                                [moles]
!c           csbmass(nsb)       = total sorbed mass in system         * +
!c                                [moles]
!c           csbmass_ion(nsb_ion) = total sorbed mass in system       * +
!c                                  [moles] (ion-exchange)
!c           csbmass_surf(nsb_surf) = total sorbed mass in system     * +
!c                                  [moles] (surface-complex)
!c           csbmass_c(nsites)  = total sorbed mass in system         * +
!c                                - non-aqueous components [moles]
!c           cculabsbal(n)      = accumulative absolute mass balance  * +
!c                                error for dissolved species
!c                                [moles/elapsed time]
!c           cculrelbal(n)      = accumulative relative mass balance  * +
!c                                error for dissolved species [%]
!c           gculabsbal(ng)     = accumulative absolute mass balance  * +
!c                                error for gaseous species
!c                                [moles/elapsed time]
!c           gculrelbal(ng)     = accumulative relative mass balance  * +
!c                                error for gaseous species [%]
!c           cmculabsbal(nm)    = accumulative absolute mass balance  * +
!c                                error for minerals
!c                                [moles/elapsed time]
!c           cmculrelbal(nm)    = accumulative relative mass balance  * +
!c                                error for minerals [%]
!c           sbdiff(n)          = source-sink term due to phase       * +
!c                                exchange with sorbed phase
!c           rateaqtot(naq)     = total rate of intra-aqueous kinetic * +
!c                                reaction in solution domain
!c                                [moles/day]
!c           contaqtot(naq)     = contribution of intra-aqueous       * +
!c                                kinetic reactions to mass balance
!c                                [moles/elapsed time]
!c           contmintot(nm)     = contribution of dissolution-        * +
!c                                precipitation reactions to mass
!c                                balance [moles/elapsed time]
!c           totdpdiffp(ndr*nm) = individual contribution of parallel * +
!c                                reaction pathways of dissolution-
!c                                precipitation reactions to mass
!c                                balance [moles/elapsed time]
!c           totcfluxin(nc)     = total mass gain due to inflow in    * +
!c                                auqueous phase in terms of total
!c                                aqueous component concentrations
!c           totcfluxout(nc)    = total mass loss due to inflow in    * +
!c                                aqueous phase in terms of total
!c                                aqueous component concentrations
!c           totcstordiff(nc)   = total change in storage in          * +
!c                                aqueous phase in terms of total
!c                                aqueous component concentrations
!c           totordiff(nc)      = total source/sink to total          * +
!c                                aqueous component concentrations
!c                                due to intra-aqueous kinetic
!c                                reactions
!c           totdpdiff(nc)      = total source/sink to total          * +
!c                                aqueous component concentrations
!c                                due to dissolution-precipitation
!c                                reactions
!c           totgdegas(nc)      = total mass los from aqueous         * +
!c                                phase due to degassing
!c           totgdiff(nc)       = total source/sink to total          * +
!c                                aqueous component concentrations
!c                                due to gas dissolution-esolution
!c                                reactions
!c           totgfluxin(nc)     = total mass gain due to inflow in    * +
!c                                gas phase in terms of total
!c                                gaseous component concentrations
!c           totgfluxout(nc)    = total mass loss due to inflow in    * +
!c                                gas phase in terms of total
!c                                gaseous component concentrations
!c           totgstordiff(nc)   = total change in storage in          * +
!c                                gas phase in terms of total
!c                                gaseous component concentrations
!c           totsbdiff(nc)      = total source/sink to total          * +
!c                                aqueous component concentrations
!c                                due to sorption or ion-exchange
!c                                reactions
!c           distcoff_rt(nc,nngl) = sorption distribution coefficient   * +
!c                                [L H_2O/L bulk] 
!c                                - reactive transport 
!c           totaold(n,nngl)      = total sorbed component              * + 
!c                                concentrations
!c                                non-competitive sorption 
!c                                - old time level [moles/l bulk]
!c           totanew(n,nngl)      = total aqueous component             * +
!c                                concentrations
!c                                non-competitive sorption
!c                                - new time level [moles/l bulk]
!c           astor(n)           = storage term (non-competitive       * +
!c                                sorption)
!c added for gas transport:
!c
!c           dens_g(nn)         = gas density                         * +
!c           gafluxin(n)        = advective gas in-flux               * +
!c           gafluxout(n)       = advective gas out-flux              * + 
!c           gmfrac(ng,nn)      = molar gas fractions                 * +
!c           mdens_g(nn)        = molar gas density                   * +
!c           totgaflux(n)       = total advective gas flux            * +
!c           totgafluxin(nc)    = total advective gas out-flux        * + 
!c           totgafluxout(nc)   = total advective gas in-flux         * +
!c           totgmfrac(n,nn)    = total molar gas fraction            * +
!c           visc_g(nn)         = gas viscosity                       * +
!c
!c ------------------------
!c
!c
!c           integer*4:
!c           ----------
!c           ilog               = unit number, logbook file           + -
!c           mpropc(nngl)         = pointer array for allocation of     * +
!c                                chemical material properties
!c           n                  = number of components excluding h2o  + -
!c                                equals number of unknowns per
!c                                control volume
!c           i2up(nngl)           = pointer array to second upstream    * +
!c                                point
!c added for gas transport:
!c
!c           dens_g(nngl)         = gas density                         * +
!c           gafluxin(n)        = advective gas in-flux               * +
!c           gafluxout(n)       = advective gas out-flux              * + 
!c           gmfrac(ng,nngl)      = molar gas fractions                 * +
!c           mdens_g(nngl)        = molar gas density                   * +
!c           totgaflux(n)       = total advective gas flux            * +
!c           totgafluxin(nc)    = total advective gas out-flux        * + 
!c           totgafluxout(nc)   = total advective gas in-flux         * +
!c           totgmfrac(n,nngl)    = total molar gas fraction            * +
!c           visc_g(nngl)         = gas viscosity 
!c
!c chem.f:   integer*4:
!c           ----------
!c           nc                 = number of components including h2o  + -
!c           ng                 = number of gases                     + -
!c           nm                 = number of minerals                  + -
!c           nx                 = number of aqueous complexes         + -
!c
!c local:    integer*4:
!c           ----------
!c           ierr               = 0 -> memory allocation successful
!c
!c external: checkerr  = check for error during memory allocation
!c
!c---------------------------------------------------------------------- 
!c WARNING
!c---------------------------------------------------------------------- 
!c All allocated variables are initialized to some value. This depends  
!c of its type:
!c 
!c real*8      => 0.0d0
!c integer     => 0 
!c character   => ' '    
!c logical     => .false. 
!c 
!c Sergio Andres Bea Jofre (2009)
!c
!c ----------------------------------------------------------------------
  
      subroutine mem_rt
 
      use parm
      use gen
      use chem
      use phys
      use bbls
      
      implicit none
      
      integer :: ierr
 
      external checkerr
      
      logical iserror

!c  allocate memory for reactive transport simulation

!c  main variables - reactive transport
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp parallel private(ierr)
    !$omp sections
#endif
#endif

#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (c(nc,nngl), stat = ierr)
      c=0.0d0
      call checkerr(ierr,'c',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (cnew(nc,nngl), stat = ierr)
      cnew=0.0d0
      call checkerr(ierr,'cnew',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (cec_g(nngl), stat = ierr)
      cec_g=0.0d0
      call checkerr(ierr,'cec_g',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (cec_fraction_g(nsites_ion, nngl), stat = ierr)
      cec_fraction_g=0.0d0
      if (nsites_ion >= 1) then
        cec_fraction_g(1,:)=1.0d0
      end if
      call checkerr(ierr,'cec_fraction_g',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (rhobulk_g(nngl), stat = ierr)
      rhobulk_g=0.0d0
      call checkerr(ierr,'rhobulk_g',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      if (nx.gt.0) then
        allocate (gamma(nc+nx,nngl), stat = ierr)
        gamma=1.0d0
        call checkerr(ierr,'gamma',ilog)
    
        if (hmulti_diff) then
              allocate (gammaold(nc+nx,nngl), stat = ierr)
              gammaold=1.0d0
              call checkerr(ierr,'gammaold',ilog)
        end if

      else
        allocate (gamma(nc+1,nngl), stat = ierr)
        gamma=1.0d0
        call checkerr(ierr,'gamma',ilog)
    
        if (hmulti_diff) then
              allocate (gammaold(nc+1,nngl), stat = ierr)
              gammaold=1.0d0
              call checkerr(ierr,'gammaold',ilog)
        end if
    
      end if
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totcold(n,nngl), stat = ierr)
      totcold=0.0d0
      call checkerr(ierr,'totcold',ilog)

      if (hmulti_diff) then
        allocate (totcoldf(n,nngl), stat = ierr)
        totcoldf=0.0d0
        call checkerr(ierr,'totcoldf',ilog)
      end if
      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totcnew(n,nngl), stat = ierr)
      totcnew=0.0d0
      call checkerr(ierr,'totcnew',ilog)
      
      if (hmulti_diff) then
        allocate (totcnewf(n,nngl), stat = ierr)
        totcnewf=0.0d0
        call checkerr(ierr,'totcnewf',ilog)
      end if
      
!c  New variables - Multicomponent Diffusion
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totviscnew(n,nngl), stat = ierr)
      totviscnew=0.0d0
      call checkerr(ierr,'totviscnew',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totviscnewMP(n,nngl), stat = ierr)
      totviscnewMP=0.0d0
      call checkerr(ierr,'totviscnewMP',ilog)
      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
      allocate (totviscnewjvol(n), stat = ierr)
      totviscnewjvol=0.0d0
      call checkerr(ierr,'totviscnewjvol',ilog) 
#endif
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (electromignew(nc,nngl), stat = ierr)
      electromignew=0.0d0
      call checkerr(ierr,'electromignew',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (electromignew_inc(nc,nngl), stat = ierr)
      electromignew_inc=0.0d0
      call checkerr(ierr,'electromignew_inc',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (zc(nngl), stat = ierr)
      zc=0.0d0
      call checkerr(ierr,'zc',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (zcabs(nngl), stat = ierr)
      zcabs=0.0d0
      call checkerr(ierr,'zcabs',ilog)
          
!c  New variables - Multicomponent Diffusion
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totgold(nc,nngl), stat = ierr)
      totgold=0.0d0
      call checkerr(ierr,'totgold',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totgnew(nc,nngl), stat = ierr)
      totgnew=0.0d0
      call checkerr(ierr,'totgnew',ilog)

#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totsold_ion(n,nngl), stat = ierr)
      totsold_ion=0.0d0
      call checkerr(ierr,'totsold_ion',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totsold_surf(n,nngl), stat = ierr)
      totsold_surf=0.0d0
      call checkerr(ierr,'totsold_surf',ilog)

      !allocate (totsnew(n,nngl), stat = ierr)
      !totsnew=0.0d0
      !call checkerr(ierr,'totsnew',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totsnew_ion(n,nngl), stat = ierr)
      totsnew_ion=0.0d0
      call checkerr(ierr,'totsnew_ion',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totsnew_surf(n,nngl), stat = ierr)
      totsnew_surf=0.0d0
      call checkerr(ierr,'totsnew_surf',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (cmold(nm,nngl), stat = ierr)
      cmold=0.0d0
      call checkerr(ierr,'cmold',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      if (nm.gt.0) then  
        allocate (cmnew(nm,nngl), stat = ierr)
        cmnew=0.0d0
        call checkerr(ierr,'cmnew',ilog)
      else
        allocate (cmnew(1,nngl), stat = ierr)  !dummy array for tprfrtlc 
        cmnew=0.0d0
        call checkerr(ierr,'cmnew',ilog)
      end if
      
!FG sept 2021--------------------------------
      if (nm.gt.0) then     
      
        allocate (sum_ratemin(nm), stat = ierr)
        sum_ratemin=0.0d0  
        call checkerr(ierr,'sum_ratemin',ilog)
                  
        allocate (sum_rmm(nm), stat = ierr)
        sum_rmm=0.0d0  
        call checkerr(ierr,'sum_rmm',ilog)
        
!        allocate (sum_rmm_cumul(nm), stat = ierr)
!        sum_rmm_cumul=0.0d0  
!        call checkerr(ierr,'sum_rmm_cumul',ilog) 
        
      endif
!---------------------------------------------
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (gold(ng,nngl), stat = ierr)
      gold=0.0d0
      call checkerr(ierr,'gold',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      if (ng.gt.0) then 
        allocate (gnew(ng,nngl), stat = ierr)
        gnew=0.0d0
        call checkerr(ierr,'gnew',ilog)
      else
        allocate (gnew(1,nngl), stat = ierr)  !dummy array for tprfrtlc
        gnew=0.0d0
        call checkerr(ierr,'gnew',ilog)
      end if
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (gmfrac(ng,nngl), stat = ierr)
      gmfrac=0.0d0
      call checkerr(ierr,'gmfrac',ilog)      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totgmfrac(n,nngl), stat = ierr)
      totgmfrac=0.0d0
      call checkerr(ierr,'totgmfrac',ilog)      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (tau(nngl), stat = ierr)
      tau=1.0d0
      call checkerr(ierr,'tau',ilog)
      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      if (nx.gt.0) then
        allocate (cx(nx,nngl), stat = ierr)
        cx=0.0d0
        call checkerr(ierr,'cx',ilog)
    
        if (hmulti_diff) then
              allocate (cxold(nx,nngl), stat = ierr)
              cxold=0.0d0
              call checkerr(ierr,'cxold',ilog)
        end if
    
      else
        allocate (cx(1,nngl), stat = ierr)
        cx=0.0d0
        call checkerr(ierr,'cx',ilog)
    
        if (hmulti_diff) then
              allocate (cxold(1,nngl), stat = ierr)
              cxold=0.0d0
              call checkerr(ierr,'cxold',ilog)
        end if
    
      end if
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (sionnew(nngl), stat = ierr)
      sionnew=0.0d0
      call checkerr(ierr,'sionnew',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (sionold(nngl), stat = ierr)
      sionold=0.0d0
      call checkerr(ierr,'sionold',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      if (nm.gt.0) then
        allocate (phi(nm,nngl), stat = ierr)
        phi=0.0d0
        call checkerr(ierr,'phi',ilog)
      else
        allocate (phi(1,nngl), stat = ierr)  !dummy array for tprfrtlc
        phi=0.0d0
        call checkerr(ierr,'phi',ilog)
      end if
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (phi_init(nm,nngl), stat = ierr)
      phi_init=0.0d0
      call checkerr(ierr,'phi_init',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (phinucthrd(nm,nngl), stat = ierr)
      phinucthrd=0.0d0
      call checkerr(ierr,'phinucthrd',ilog) 
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (area_init(nm,nngl), stat = ierr)
      area_init=0.0d0
      call checkerr(ierr,'area_init',ilog)  
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (areanucthrd(nm,nngl), stat = ierr)
      areanucthrd=0.0d0
      call checkerr(ierr,'areanucthrd',ilog)  
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      if (nm.gt.0) then
        allocate (phiold(nm,nngl), stat = ierr)
        phiold=0.0d0
        call checkerr(ierr,'phiold',ilog)
      else
        allocate (phiold(1,nngl), stat = ierr)  !dummy array for tprfrtlc
        phiold=0.0d0
        call checkerr(ierr,'phiold',ilog)
      end if      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      if (nm.gt.0) then
        allocate (area(nm,nngl), stat = ierr)
        area=0.0d0
        call checkerr(ierr,'area',ilog)
      else
        allocate (area(1,nngl), stat = ierr)  !dummy array for tprfrtlc
        area=0.0d0
        call checkerr(ierr,'area',ilog)
      end if
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (mpropc(nngl), stat = ierr)
      mpropc=0
      call checkerr(ierr,'mpropc',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totanew(nc,nngl), stat = ierr)
      totanew=0.0d0
      call checkerr(ierr,'totanew',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totaold(nc,nngl), stat = ierr)
      totaold=0.0d0
      call checkerr(ierr,'totaold',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (distcoff_rt(nc,nngl), stat = ierr)
      distcoff_rt=0.0d0
      call checkerr(ierr,'distcoff_rt',ilog)

!cprovi-------------------------------------------------------------
!cprovi-------------------------------------------------------------
!cprovi-------------------------------------------------------------
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (diff_ic(nc), stat = ierr)
      diff_ic=0.0d0 
      call checkerr(ierr,'diff_ic',ilog)    
!cprovi-------------------------------------------------------------
!cprovi-------------------------------------------------------------
!cprovi-------------------------------------------------------------
!cmx-------------------------------------------------------------
      allocate (f_epor(nc), stat = ierr)
      f_epor=1.0d0 
      call checkerr(ierr,'f_epor',ilog)    
      
      allocate (f_etau(nc), stat = ierr)
      f_etau=1.0d0 
      call checkerr(ierr,'f_etau',ilog)  
    
!cmx-------------------------------------------------------------
!c  newton iteration - reactive transport
      allocate (cflux(ncon,n), stat = ierr)
      cflux=0.0d0
      call checkerr(ierr,'cflux',ilog)

      allocate (cstor(n), stat = ierr)
      cstor=0.0d0
      call checkerr(ierr,'cstor',ilog)

      allocate (gflux(ncon,n), stat = ierr)
      gflux=0.0d0
      call checkerr(ierr,'gflux',ilog)

      allocate (gstor(n), stat = ierr)
      gstor=0.0d0
      call checkerr(ierr,'gstor',ilog)

      allocate (dtotcflux(n), stat = ierr)
      dtotcflux=0.0d0
      call checkerr(ierr,'dtotcflux',ilog)

      allocate (dtotgflux(n), stat = ierr)
      dtotgflux=0.0d0
      call checkerr(ierr,'dtotgflux',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (ratemdp(nm,nngl), stat = ierr)
      ratemdp=0.0d0
      call checkerr(ierr,'ratemdp',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totcflux(n), stat = ierr)
      totcflux=0.0d0
      call checkerr(ierr,'totcflux',ilog)

      allocate (totcflux_diff(n), stat = ierr)         !MCD
      totcflux_diff=0.0d0
      call checkerr(ierr,'totcflux_diff',ilog)
      
      allocate (totcflux_mig(n), stat = ierr)          !MCD
      totcflux_mig=0.0d0
      call checkerr(ierr,'totcflux_mig',ilog)
      
      allocate (totgflux(n), stat = ierr)
      totgflux=0.0d0
      call checkerr(ierr,'totgflux',ilog)
      
      allocate (totgaflux(n), stat = ierr)
      totgaflux=0.0d0
      call checkerr(ierr,'totgaflux',ilog)
      
      allocate (gafluxin(n), stat = ierr)
      gafluxin = 0.0d0
      call checkerr(ierr,'gafluxin',ilog)

      allocate (gafluxout(n), stat = ierr)
      gafluxout = 0.0d0
      call checkerr(ierr,'gafluxout',ilog)
      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totmdp(n,nngl), stat = ierr)
      totmdp=0.0d0
      call checkerr(ierr,'totmdp',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (astor(n), stat = ierr)
      astor=0.0d0
      call checkerr(ierr,'astor',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (i2up(nngl), stat = ierr)
      i2up=0 
      call checkerr(ierr,'i2up',ilog)

!c  data structure and solver - reactive transport
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (brt(nngl*n), stat = ierr)
      brt=0.0d0
      call checkerr(ierr,'brt',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (urt(nngl*n), stat = ierr)
      urt=0.0d0
      call checkerr(ierr,'urt',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (resrt(nngl*n), stat = ierr)
      resrt=0.0d0
      call checkerr(ierr,'resrt',ilog)
      
      !b_doublecheck_residual = .true.
      !if(b_doublecheck_residual) then
      !    allocate (resrt_check(nngl*n), stat = ierr)
      !    restrt_check=0.0d0
      !    call checkerr(ierr,'resrt_check',ilog)   
      !end if
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (iart(nngl*n+1), stat = ierr)
      iart=0
      call checkerr(ierr,'iart',ilog)
#ifdef PETSC
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (row_idx_l2pg_rt(nngl*n+1), stat = ierr)
      row_idx_l2pg_rt=0
      call checkerr(ierr,'row_idx_l2pg_rt',ilog)      
#endif
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (kbl(n,n), stat = ierr)
      kbl=0
      call checkerr(ierr,'kbl',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (kblsorb(n,n), stat = ierr)
      kblsorb=0
      call checkerr(ierr,'kblsorb',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (kblredox(n,n), stat = ierr)
      kblredox=0
      call checkerr(ierr,'kblredox',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (iafrt(nngl*n+1), stat = ierr)
      iafrt=0
      call checkerr(ierr,'iafrt',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (iafdrt(nngl*n), stat = ierr)
      iafdrt=0
      call checkerr(ierr,'iafdrt',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (lorderrt(nngl*n), stat = ierr)
      lorderrt=0
      call checkerr(ierr,'lorderrt',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (invordrt(nngl*n), stat = ierr)
      invordrt=0
      call checkerr(ierr,'invordrt',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (iadbl(n+1), stat = ierr)
      iadbl=0
      call checkerr(ierr,'iadbl',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (jadbl(n*n), stat = ierr)
      jadbl=0
      call checkerr(ierr,'jadbl',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (kadbl(n,n), stat = ierr)
      kadbl=0
      call checkerr(ierr,'kadbl',ilog)

      allocate (iaobl(n+1), stat = ierr)
      iaobl=0
      call checkerr(ierr,'iaobl',ilog)

      allocate (jaobl(n*n), stat = ierr)
      jaobl=0
      call checkerr(ierr,'jaobl',ilog)

      allocate (kaobl(n,n), stat = ierr)
      kaobl=0
      call checkerr(ierr,'kaobl',ilog)

!c  mass balance - reactive transport
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (cfluxin(n), stat = ierr)
      cfluxin=0.0d0
      call checkerr(ierr,'cfluxin',ilog)

      allocate (cfluxin_diff(n), stat = ierr)       !MCD
      cfluxin_diff=0.0d0
      call checkerr(ierr,'cfluxin_diff',ilog)

      allocate (cfluxin_mig(n), stat = ierr)        !MCD
      cfluxin_mig=0.0d0
      call checkerr(ierr,'cfluxin_mig',ilog)

      allocate (cfluxout(n), stat = ierr)
      cfluxout=0.0d0
      call checkerr(ierr,'cfluxout',ilog)

      allocate (cfluxout_diff(n), stat = ierr)         !MCD
      cfluxout_diff=0.0d0
      call checkerr(ierr,'cfluxout_diff',ilog)

      allocate (cfluxout_mig(n), stat = ierr)          !MCD
      cfluxout_mig=0.0d0
      call checkerr(ierr,'cfluxout_mig',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (gfluxtbdy(ng), stat = ierr)
      gfluxtbdy=0.0d0
      call checkerr(ierr,'gfluxtbdy',ilog)

      allocate (gfluxin(n), stat = ierr)
      gfluxin=0.0d0
      call checkerr(ierr,'gfluxin',ilog)

      allocate (gfluxout(n), stat = ierr)
      gfluxout=0.0d0
      call checkerr(ierr,'gfluxout',ilog)

      allocate (cstordiff(n+nm), stat = ierr)
      cstordiff=0.0d0
      call checkerr(ierr,'cstordiff',ilog)

      allocate (gdegas(n), stat = ierr)
      gdegas=0.0d0
      call checkerr(ierr,'gdegas',ilog)

      allocate (gstordiff(n), stat = ierr)
      gstordiff=0.0d0
      call checkerr(ierr,'gstordiff',ilog)
      
      allocate (ordiff(n), stat = ierr)
      ordiff=0.0d0
      call checkerr(ierr,'ordiff',ilog)

      allocate (dpdiff(n+nm), stat = ierr)
      dpdiff=0.0d0
      call checkerr(ierr,'dpdiff',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (gdiff(n+ng), stat = ierr)
      gdiff=0.0d0
      call checkerr(ierr,'gdiff',ilog)

      allocate (amass(n), stat = ierr)
      amass=0.0d0
      call checkerr(ierr,'amass',ilog)
      
      allocate (amass_gbl(n), stat = ierr)
      amass_gbl=0.0d0
      call checkerr(ierr,'amass_gbl',ilog)

      allocate (tmass(n), stat = ierr)
      tmass=0.0d0
      call checkerr(ierr,'tmass',ilog)
      
      allocate (tmass_gbl(n), stat = ierr)
      tmass_gbl=0.0d0
      call checkerr(ierr,'tmass_gbl',ilog)

      allocate (cmass(n), stat = ierr)
      cmass=0.0d0
      call checkerr(ierr,'cmass',ilog)
      
      allocate (cmass_gbl(n), stat = ierr)
      cmass_gbl=0.0d0
      call checkerr(ierr,'cmass_gbl',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (gmass(ng), stat = ierr)
      gmass=0.0d0
      call checkerr(ierr,'gmass',ilog)
      
      allocate (gmass_gbl(ng), stat = ierr)
      gmass_gbl=0.0d0
      call checkerr(ierr,'gmass_gbl',ilog)

      allocate (cmmass(nm), stat = ierr)
      cmmass=0.0d0
      call checkerr(ierr,'cmmass',ilog)
     
      allocate (cmmass_gbl(nm), stat = ierr)
      cmmass_gbl=0.0d0
      call checkerr(ierr,'cmmass_gbl',ilog)
      
      !if(nsb > 0) then
      !    allocate (csbmass(nsb), stat = ierr)
      !    csbmass=0.0d0
      !    call checkerr(ierr,'csbmass',ilog)
      !end if
      
      if(nsb_ion > 0) then
          allocate (csbmass_ion(nsb_ion), stat = ierr)
          csbmass_ion=0.0d0
          call checkerr(ierr,'csbmass_ion',ilog)
          
          allocate (csbmass_ion_gbl(nsb_ion), stat = ierr)
          csbmass_ion_gbl=0.0d0
          call checkerr(ierr,'csbmass_ion_gbl',ilog)
      end if
      
      if(nsb_surf > 0) then
          allocate (csbmass_surf(nsb_surf), stat = ierr)
          csbmass_surf=0.0d0
          call checkerr(ierr,'csbmass_surf',ilog)
          
          allocate (csbmass_surf_gbl(nsb_surf), stat = ierr)
          csbmass_surf_gbl=0.0d0
          call checkerr(ierr,'csbmass_surf_gbl',ilog)
      end if
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (csbmass_c(nsites), stat = ierr)
      csbmass_c=0.0d0
      call checkerr(ierr,'csbmass_c',ilog)
      
      allocate (csbmass_c_gbl(nsites), stat = ierr)
      csbmass_c_gbl=0.0d0
      call checkerr(ierr,'csbmass_c_gbl',ilog)

      allocate (cculabsbal(n), stat = ierr)
      cculabsbal=0.0d0
      call checkerr(ierr,'cculabsbal',ilog)

      allocate (cculrelbal(n), stat = ierr)
      cculrelbal=0.0d0
      call checkerr(ierr,'cculrelbal',ilog)

      allocate (gculabsbal(ng), stat = ierr)
      gculabsbal=0.0d0
      call checkerr(ierr,'gculabsbal',ilog)

      allocate (gculrelbal(ng), stat = ierr)
      gculrelbal=0.0d0
      call checkerr(ierr,'gculrelbal',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (cmculabsbal(nm), stat = ierr)
      cmculabsbal=0.0d0
      call checkerr(ierr,'cmculabsbal',ilog)

      allocate (cmculrelbal(nm), stat = ierr)
      cmculrelbal=0.0d0
      call checkerr(ierr,'cmculrelbal',ilog)

      allocate (sbdiff(n), stat = ierr)
      sbdiff=0.0d0
      call checkerr(ierr,'sbdiff',ilog)

      allocate (rateaqtot(naq), stat = ierr)
      rateaqtot=0.0d0
      call checkerr(ierr,'rateaqtot',ilog)

      allocate (contaqtot(naq), stat = ierr)
      contaqtot=0.0d0
      call checkerr(ierr,'contaqtot',ilog)

      allocate (contmintot(nm), stat = ierr)
      contmintot=0.0d0
      call checkerr(ierr,'contmintot',ilog)
      
#ifdef PETSC
      allocate (contmintot_mpi(nm), stat = ierr)
      contmintot_mpi=0.0d0
      call checkerr(ierr,'contmintot_mpi',ilog)
#endif
      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totcfluxin(nc), stat = ierr)
      totcfluxin=0.0d0
      call checkerr(ierr,'totcfluxin',ilog)

      allocate (totcfluxin_diff(nc), stat = ierr)     !MCD
      totcfluxin_diff=0.0d0
      call checkerr(ierr,'totcfluxin_diff',ilog)
      
      allocate (totcfluxin_mig(nc), stat = ierr)      !MCD
      totcfluxin_mig=0.0d0
      call checkerr(ierr,'totcfluxin_mig',ilog)
      
      allocate (totcfluxout(nc), stat = ierr)
      totcfluxout=0.0d0
      call checkerr(ierr,'totcfluxout',ilog)

      allocate (totcfluxout_diff(nc), stat = ierr)       !MCD
      totcfluxout_diff=0.0d0
      call checkerr(ierr,'totcfluxout_diff',ilog)
      
      allocate (totcfluxout_mig(nc), stat = ierr)        !MCD
      totcfluxout_mig=0.0d0
      call checkerr(ierr,'totcfluxout_mig',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totcstordiff(nc), stat = ierr)
      totcstordiff=0.0d0
      call checkerr(ierr,'totcstordiff',ilog)

      allocate (totordiff(nc), stat = ierr)
      totordiff=0.0d0
      call checkerr(ierr,'totordiff',ilog)

      allocate (totdpdiff(nc), stat = ierr)
      totdpdiff=0.0d0
      call checkerr(ierr,'totdpdiff',ilog)

      allocate (totgdegas(nc), stat = ierr)
      totgdegas=0.0d0
      call checkerr(ierr,'totgdegas',ilog)

      allocate (totgdiff(nc), stat = ierr)
      totgdiff=0.0d0
      call checkerr(ierr,'totgdiff',ilog)
      
!c    gas phase density, molar density, viscosity
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (dens_g(nngl), stat = ierr)
      dens_g = 0.0d0
      call checkerr(ierr,'dens_g',ilog) 
    
      allocate (visc_g(nngl), stat = ierr)
      visc_g = 0.0d0
      call checkerr(ierr,'visc_g',ilog) 
      
      allocate (mdens_g(nngl), stat = ierr)
      mdens_g = 0.0d0
      call checkerr(ierr,'mdens_g',ilog) 
      
      allocate (dg(ng), stat = ierr)
      dg = 0.0d0
      call checkerr(ierr,'dg',ilog)
      
      allocate (gdens(nngl), stat = ierr)
      gdens = 0.0d0
      call checkerr(ierr,'gdens',ilog)
      
      allocate (gij(ng), stat = ierr)
      gij = 0.0d0
      call checkerr(ierr,'gij',ilog)
      
      allocate (gvisc(nngl), stat = ierr)
      gvisc = 0.0d0
      call checkerr(ierr,'gvisc',ilog)
      
      allocate (gpivol(nngl), stat = ierr)
      gpivol = 0.0d0
      call checkerr(ierr,'gpivol',ilog)
      
      allocate (gmfracij(ng), stat = ierr)
      gmfracij = 0.0d0
      call checkerr(ierr,'gmfracij',ilog)
      
      allocate (gmfrac_brt(ng), stat = ierr)
      call checkerr(ierr,'',ilog)
      
      allocate (gmfrac_ivol(ng), stat = ierr)
      gmfrac_ivol = 0.0d0
      call checkerr(ierr,'gmfrac_ivol',ilog)
      
      allocate (totgnew_brt(nc), stat = ierr)
      totgnew_brt = 0.0d0
      call checkerr(ierr,'totgnew_brt',ilog)
      
      allocate (totgmfrac_brt(nc), stat = ierr)
      totgmfrac_brt = 0.0d0
      call checkerr(ierr,'totgmfrac_brt',ilog)
      
      allocate (totgmfrac_ivol(nc), stat = ierr)
      totgmfrac_ivol = 0.0d0
      call checkerr(ierr,'totgmfrac_ivol',ilog)
      
      allocate (totgij(nc), stat = ierr)
      totgij = 0.0d0
      call checkerr(ierr,'totgij',ilog)
      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (totgfluxin(nc), stat = ierr)
      totgfluxin=0.0d0
      call checkerr(ierr,'totcfluxin',ilog)

      allocate (totgfluxout(nc), stat = ierr)
      totgfluxout=0.0d0
      call checkerr(ierr,'totgfluxout',ilog)
      
      allocate (totgafluxin(nc), stat = ierr)
      totgafluxin = 0.0d0
      call checkerr(ierr,'totgafluxin',ilog)

      allocate (totgafluxout(nc), stat = ierr)
      totgafluxout = 0.0d0
      call checkerr(ierr,'totgfluxout',ilog)

      allocate (totgstordiff(nc), stat = ierr)
      totgstordiff=0.0d0
      call checkerr(ierr,'totgstordiff',ilog)

      allocate (totsbdiff(nc), stat = ierr)
      totsbdiff=0.0d0
      call checkerr(ierr,'totsbdiff',ilog)
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp section
#endif
#endif
      allocate (dpdiffp(maxndr*nm), stat = ierr)
      dpdiffp=0.0d0
      call checkerr(ierr,'dpdiffp',ilog)

      allocate (totdpdiffp(maxndr*nm), stat = ierr)
      totdpdiffp=0.0d0
      call checkerr(ierr,'totdpdiffp',ilog)
      
!c_bubbles variables for bubble problem

      if (gas_bubbles) then

        allocate (uvsnew_b(nngl), stat = ierr)
        uvsnew_b=0.0d0
        call checkerr(ierr,'uvsnew_b',ilog)
        
        allocate (sanew_c(nngl), stat = ierr)
        sanew_c=0.0d0
        call checkerr(ierr,'sanew_c',ilog)
        
        allocate (sanew_b(nngl), stat = ierr)
        sanew_b=0.0d0
        call checkerr(ierr,'sanew_b',ilog)
        
        allocate (c_update(nc,nngl), stat = ierr)
        c_update=0.0d0
        call checkerr(ierr,'c_update',ilog)
        
        allocate (tot_gas(ng,nngl), stat = ierr)
        tot_gas=0.0d0
        call checkerr(ierr,'tot_gas',ilog)
                
        allocate (k_henry(ng,nngl), stat = ierr)
        k_henry=0.0d0
        call checkerr(ierr,'k_henry',ilog)
        
      end if

!c_bubbles 

      allocate (scalfac_aq_ivol(naq,nngl), stat = ierr)
      scalfac_aq_ivol=0.0d0
      call checkerr(ierr,'scalfac_aq_ivol',ilog)
      
#ifdef PETSC
      allocate (totdpdiffp_mpi(maxndr*nm), stat = ierr)
      totdpdiffp_mpi=0.0d0
      call checkerr(ierr,'totdpdiffp_mpi',ilog)
#endif
      
      allocate (mpireduce_n(n), stat = ierr)
      mpireduce_n=0.0d0
      call checkerr(ierr,'mpireduce_n',ilog)
      
      allocate (mpireduce_ng(ng), stat = ierr)
      mpireduce_ng=0.0d0
      call checkerr(ierr,'mpireduce_ng',ilog)
      
      allocate (mpireduce_nm(nm), stat = ierr)
      mpireduce_nm=0.0d0
      call checkerr(ierr,'mpireduce_nm',ilog)
      
      allocate (mpireduce_naq(naq), stat = ierr)
      mpireduce_naq=0.0d0
      call checkerr(ierr,'mpireduce_naq',ilog)      
      
#ifdef OPENMP
#ifdef PARALLEL_SECTION
    !$omp end sections
    !$omp end parallel
#endif
#endif 
      return
      end
