!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 491 $
!> $Author: fgerard $
!> $Date: 2017-07-18 00:06:39 +0200 (Tue, 18 Jul 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/modrate.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine modrate
!c ------------------
!c
!c modify reaction rate of minerals dependent on several constraints
!c
!c written by:      Uli Mayer - Nov 4, 1997
!c
!c last modified:   -
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   real*8:
!c           -------
!c           ratem              = absolute dissolution-precipitation  + -
!c                                rate of mineral
!c           cmnewm             = concentration of mineral            + -
!c                                - new time level [moles/l bulk]
!c           delt               = time step                           + -
!c
!c           integer*4:
!c           ----------
!c           im                 = pointer (current mineral)           + -
!c
!c common:   
!c chem.f:   real*8:
!c           -------
!c           cmcmin(nm,nthreads)= min. concentration of minerals      + -
!c                                [moles/l bulk]
!c           ratemp(ndr*nm,nthreads)
!c                              = reaction rates for minerals         + +
!c                                including parallel reactions
!c           satm(nm,nthreads)  = saturation indices                  + -
!c           supsatm(nm)        = level of supersaturation required   + -
!c                                for precipitation [log cycles]
!c           tinyrate           = set reaction rates to zero,         + -
!c                                if smaller than tinyrate
!c
!c           integer*4:
!c           ----------
!c           iamd(nm+1)         = pointer array to dissolution-       + -
!c                                precipitation reactions
!c
!c           logical:
!c           --------
!c           far_from_equil(nm) = .true.  -> far from equilibrium     + -
!c
!c           character:
!c           ---------
!c           reaction_type(nm)  = 'reversible'                        + -
!c                                'dissolution_to_equilibrium'
!c                                'precipitation_to_equilibrium'
!c                                'dissolution_far_from_equilibrium'
!c                                'precipitation_far_from_equilibrium'
!c                                'monod'
!c                                'raoult'
!c
!c local:    real*8:
!c           -------
!c           dissvol            = projected dissolved mineral
!c                                volume
!c           r0                 = constant
!c           r1                 = constant
!c           ratem_mod          = absolute dissolution-precipitation
!c                                rate of mineral (modified)
!c           small              = small increment
!c
!c           integer*4:
!c           ----------
!c           im                 = pointer (current mineral)
!c           ireac              = counter (parallel reactions)
!c           istart             = pointer
!c           istop              = pointer
!c
!c external: -
!c ----------------------------------------------------------------------
 
      subroutine modrate(ratem,cmnewm,delt,im)
 
      use parm
      use chem
#ifdef OPENMP
      use omp_lib 
#endif

      implicit none
      
      real*8 :: ratem, cmnewm, delt
      integer :: im
      
      integer :: tid, istart, iend, ireac

      real*8 :: r0, r1, small, dissvol, ratem_mod

      parameter (r0 = 0.0d0, r1 = 1.0d0, small = 1.d-10)
      
#ifdef OPENMP
      tid = omp_get_thread_num() + 1
#else
      tid = 1
#endif

!c  loop over parallel reactions

      istart = iamd(im)
      iend = iamd(im+1)-1
      
      !info_debug = 1

      do ireac = istart, iend

!c  set parallel reaction rate to zero, if absolute value of total reaction
!c  rate very small 

        if (dabs(ratem).lt.tinyrate) then
          
          ratemp(ireac,tid) = r0

        end if
     
!c  use computed parrallel rate only, if sufficient mineral mass
!c  is available, otherwise: assign reaction rate leading to 
!c  depletion of mineral

        dissvol = ratem*delt

        if (reaction_type(im).eq.'reversible' .or.                     &
     &     reaction_type(im).eq.'monod' .or.                           &
     &     reaction_type(im).eq.'dissolution_far_from_equilibrium' .or.&
     &     (reaction_type(im).eq.'dissolution_to_equilibrium') ) then

          if ((cmnewm+dissvol).lt.(r1+small)*cmcmin(im,tid)) then

!c  modified total reaction rate
            if (isofrac(im)) then
                
              ratemp(ireac, tid) = r0  
                
            else

              ratem_mod = - (cmnewm-cmcmin(im,tid))/delt

!c  scale parallel reaction rate based on modified total reaction
!c  rate and original total reaction rate

              !ratemp(ireac,tid) = ratemp(ireac,tid) * ratem_mod/ratem   
            
              !bug, for some simulation (concrete-clay benchmarking), ratem will be equal zero. DSU, 2013-2-8
              !fix: 1. change the default value of tinyrate from 0 to 1.0E-300; 2. Add continue (above) or change as follows.
              if (dabs(ratem) .eq. r0) then
                  ratemp(ireac,tid) = r0
              else
                  ratemp(ireac,tid) = ratemp(ireac,tid) * ratem_mod/ratem
              end if
              !
              !if (info_debug > 0) then
              !    if (isnan(ratemp(ireac))) then
              !        write(idgb, *) "modrate.F90, NaN in ratemp(",&
              !                    ireac,"), ratem_mod:", ratem_mod, ", ratem:", ratem    
              !    end if
              !end if
            end if

          end if

        end if

!c  set parallel reaction rate to zero, if total reaction rate indicates
!c  precipitation, but specified level of supersaturation is not 
!c  reached

        if (.not.far_from_equil(im)) then
          if (dlog10(satm(im,tid)).lt.supsatm(im).and.                &
     &        ratem.gt.r0) then
            ratemp(ireac,tid) = r0
          end if
        end if

      end do             !loop over parallel reactions
      
      !info_debug = 0

      return
      end
