!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 453 $
!> $Author: dsu $
!> $Date: 2017-02-21 19:54:05 +0100 (Tue, 21 Feb 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/rate_gasmin.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine rate_gasmin
!c ----------------------
!c
!c compute rate for gas pressure approximation mineral
!c
!c sign convention: dissolution -
!c                  precipitation +
!c
!c written by:      Uli Mayer - November 11, 01
!c
!c last modified: 
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:  
!c ----------------------------------------------------------------------
  
      subroutine rate_gasmin(ratem,im,iv,aream)
 
      use parm
      use chem
      use gen
      use phys
#ifdef OPENMP
      use omp_lib 
#endif
 
      implicit none
      
      real*8 :: ratem, aream
      integer :: im, iv, tid

      real*8, parameter :: r0 = 0.0d0, r1 = 1.0d0
      
      integer :: ig, ireac, izn 
      real*8 :: pres_tot, pres_n2
      
#ifdef OPENMP
      tid = omp_get_thread_num() + 1
#else
      tid = 1
#endif

!c  initialize total reaction rate

      ratem = r0

!c check to see if control volume is unsaturated

      izn = mpropvs(iv) 

      if (uvsnew(iv).lt.aentry(izn)) then

!c  compute total gas pressure

        pres_tot = r0
        do ig = 1,ng
          pres_tot = pres_tot + rgasatm*tkel(iv)*gnew(ig,iv)
        if(nameg(ig).eq.'n2(g)') then
          pres_n2 = rgasatm*tkel(iv)*gnew(ig,iv)
        end if
        end do

!c  calculate saturation index for current mineral 

        satm(im,tid) = pres_tot/pres_atm


!c  compute total dissolution/precipitation rate for surface controlled
!c  dissolution/precipitation reactions

        ireac = iamd(im)

        ratem = -rated(ireac,tid)*aream*(r1 - satm(im,tid))*           &
                 (pres_n2/(pres_n2+0.01))
                   
      end if

      return
      end
