!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 453 $
!> $Author: dsu $
!> $Date: 2017-02-21 19:54:05 +0100 (Tue, 21 Feb 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/reactran_2.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine reactran_2
!c -------------------
!c
!c second half of driver subroutine for reactive transport to be called
!c only after bubble routine has converged
!c
!c written by:      Rich Amos - April 19, 2004
!c
!c last modified:  
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   -
!c
!c common:
!c gen.f:    real*8:
!c           -------
!c           tfinal             = final solution time                 + -
!c           time               = current solution time               + -
!c           time_io            = current solution time (I/O units)   + -
!c           tsrc(ntsrc)        = target read times - transient       + -
!c                                source chemistry
!c                                (reactive transport)
!c           integer*4:
!c           ----------
!c           ilog               = unit number, log book               + -
!c           itsrc              = pointer to target read time for     + +
!c                                transient source chemistry
!c                                (reactive transport)
!c           ntsrc              = pointer to target read times for    + -
!c                                transient source chemistry
!c           logical:
!c           --------
!c           mass_balance_rt    = .true.  -> compute mass balance     + -
!c                                           (reactive transport)
!c           transient_source   = .true.  -> transient source         + -
!c                                           chemistry
!c           character:
!c           ----------
!c           time_unit          = time unit for output -> 'years'     + -
!c                                                        'days'
!c                                                        'hours'
!c                                                        'seconds'
!c           update_activity_rt = 'no_update' -> unity activity       + -
!c                                 coefficients
!c                                'time_lagged' -> update activity
!c                                 coefficients after each time step
!c                                'double_update' -> double update
!c                                 of activity coefficients during
!c                                 Newton iterations
!c                                 (reactive transport)
!c chem.f:   character:
!c           ----------
!c           update_activity    = 'no_update' -> unity activity       + +
!c                                 coefficients
!c                                'time_lagged' -> update activity
!c                                 coefficients after each time step
!c                                'double_update' -> double update
!c                                 of activity coefficients during
!c                                 Newton iterations
!c
!c local:    real*8:
!c           -------
!c           tiny_time          = tiny time increment
!c
!c external:mbalrt   = compute mass balance (reactive transport)
!c          tsteprt  = estimate of time step (reactive transport)
!c ----------------------------------------------------------------------

      subroutine reactran_2
 
      use parm
      use gen
      use chem
#ifdef OPENMP
      use omp_lib 
#endif
 
      implicit none

      external mbalrt, tsteprt
      
      integer :: i, ivol

      real*8, parameter :: tiny_time = 1.0d-10

!c  update concentrations of minerals, mineral volumes and
!c  reactivity term 
#ifdef OPENMP
    !$omp parallel                                                    &
    !$omp if (nngl > numofloops_thred_global)                         &
    !$omp num_threads(numofthreads_global)                            &
    !$omp default(shared)                                             &
    !$omp private (ivol)                               
    !$omp do schedule(static)
#endif
      do ivol=1,nngl

!c  exclude first type boundary control volumes

        if (btypert(ivol).ne.'first') then
!c  temperature corrections for debye-huckel, equilibrium and
!c  rate constants
          if (nm.gt.0) then
            call updtsvmp(cmnew(1,ivol),cmold(1,ivol),phi(1,ivol),     &
                          area(1,ivol),ratemdp(1,ivol),delt,ivol)
          end if
        end if

      end do
#ifdef OPENMP
    !$omp end do
    !$omp end parallel
#endif

!c  mass balance computation for reactive transport

      if (mass_balance_rt) then
        call mbalrt
      end if
      
      if (flux_out) then
        call mbal_mcd
      end if

!c  smr: decide upstream weighting for gases in the next time step

      if (spatial_weighting.eq.'upstream') then
        call giups
      endif

!c  smr: calculate the production/consumption rate of water

      if (chemical_water) then
        call rateh2o
	  endif
      
!c  estimate time increment size for next time step

      call tsteprt
      
      return

!c  update source chemistry at specified target read times
!c  this part is never called
!      if (transient_source) then
!        if (itsrc.le.ntsrc.and.tsrc(itsrc)-tiny_time.lt.time) then
!
!          if (rank == 0 .and. b_enable_output) then
!!c  report to log file
!            write(ilog,'(/a,1pe12.4,1x,a)')                            &
!                 'update source chemistry - reactive transport, T = ', &
!                  time_io, time_unit
!            write(ilog,'(72a/)')('-',i=1,72)
!
!!c  report to screen
!            write(*,'(/1x,a,1pe12.4,1x,a)')                            &
!                 'update source chemistry - reactive transport, T = ', &
!                  time_io, time_unit
!            write(*,'(1x,72a/)')('-',i=1,72)
!          
!          end if
!
!!c  update boundary conditions
!
!          call tranbcrt
!
!!c  set index for next target read time
!
!          itsrc = itsrc+1
!
!!c  set target read time to time larger than final solution time after
!!c  last update of boundary conditions
!
!          if (itsrc.gt.ntsrc) then
!            tsrc(itsrc) = tfinal+tiny_time
!          end if
!
!!c  redefine activity update technique for reactive transport
!
!          if (update_activity_rt.eq.'no_update') then
!           update_activity = 'no_update'
!          elseif (update_activity_rt.eq.'time_lagged') then
!            update_activity = 'time_lagged'
!          elseif (update_activity_rt.eq.'double_update') then
!            update_activity = 'double_update'
!          endif
!
!        end if
!      end if

      return
      end
