!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 488 $
!> $Author: cblitz $
!> $Date: 2017-07-17 18:22:05 +0200 (lun. 17 juil. 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/cblitz_1/src/min3p/rootwat.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c -----------------------------------------------------------------------
!c real*8 function rew
!c -----------------------
!c compute reserve of extractible water : used to calculate mean value for alpha-correction method 2
!c
!c written by:      Fred Gérard - Oct, 07
!c                  alpha function applied to transpiration : REW profile scale used
!c
!c   definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   real*8:
!c           -------
!c           satwnew(nn)        = aqueous phase saturation             + -
!c                                - new time level
!c
!c           integer*4:
!c           ----------
!c           ivol               = pointer to current volume
!c
!c          
!c common:   
!c
!c gen.f     real*8
!c           ------
!c           cvol(nn)           = nodal volumes
!c           pet                = potential evapotranspiration
!c           scale_tree_growth  = scale factor to account for the influence
!c                                of the tree growth on transpiration
!c           delz(nvz)          = spatial increment in z-direction 
!c          
!c           integer*4
!c           ------
!c           nn                 = total number of control volumes 
!c           mpropvs(nn)        = pointer array to volume properties
!c           ilog               = unit number, log book               + -
!c
!c phys.f:   real*8:
!c           ------- 
!c           rew0               = relative extractable water at       + -
!c                                50% of maximum extraction capacity 
!c                                (fitting parameter)
!c           p1                 = fitting parameter for root water    + -
!c                                uptake function
!c           satwlim(nzn)       = water saturation at wilting point   + -
!c           satwfield(nzn)     = water saturation at field capacity  + -
!c           rootlengthdens(nzn)= root length density
!c           rld(nn)            = root length density read from external file
!c
!c local:    rew                = relative extractable water
!c           r0                 = constant
!c           r1                 = constant
!c           r2                 = constant
!c           v_prop             = proportion of actual transpiration in current volume
!c           vsum               = total volume
!c           transp             = transpiration flux
!c           alpha              = reduction factor for transpiration
!c           rsum               = total root transpiration
!c           izn                = pointer to material property zone
!c
!c external: -
!c ----------------------------------------------------------------------
 
      real*8 function rew(satwnew,ivol)
 
      use parm
      use phys
      use gen
	use biol

!	implicit real*8 (a-h,o-z)
      parameter (r0 = 0.0d0, r1 = 1.0d0, r2 = 2.0d0, r4 = 4.0d0)
      parameter (r1p5 = 1.5d0)

      real*8 satwnew(*)!,xareatop
      !integer iiii,j,i CBF
      !logical first CBF

      !data first /.true./ CBF
      !save xareatop,first CBF

!c  setup pointer to the material properties of the current volume     

	izn = mpropvs(ivol)
!CBF	write(*,*) '************* REW.F90 ****************'
!	write(*,*) 'izn=', izn

!c calculate reserve of extractible water in each control volume

      rew = dmin1((satwnew(ivol)-satwlim(izn))/(satwfield(izn)-satwlim(izn)),r1)
! CBF :
!        write(*,*) 'satwnew(ivol)=', satwnew(ivol)
!        write(*,*) 'satwlim(izn)=', satwlim(izn)
!        write(*,*) 'satwfield(izn)=', satwfield(izn)
!        write(*,*) 'r1=', r1

!c
      return

	end
