!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 453 $
!> $Author: dsu $
!> $Date: 2017-02-21 19:54:05 +0100 (Tue, 21 Feb 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/trans_evap_info.F90 $
!---------------------------------------------------------------------
!********************************************************************!

subroutine trans_evap_info (isinitial,ngb_tstep)
 
use parm
use gen
use phys
use dens
use chem 
use writeversion
use m_heat_transport, only : offset_ievap, offset_ievap_ijk

use module_binary_mpiio, only : binary_file_open,                     &
                                 tecplot_binary_write_header,          &
                                 tecplot_binary_write_variable,        &
                                 tecplot_binary_write_zoneinfo,        &
                                 tecplot_binary_write_section,         &
                                 binary_write_data

implicit none
#ifdef PETSC_V3_6_X
#include <petsc/finclude/petscsys.h>
#elif PETSC
#include <finclude/petscsys.h>
#endif

logical :: isinitial
integer :: ngb_tstep

real*8 dummy1, dummy2, dummy3, dummy4, evaploc, hsloc, levaploc,       &
       pvloc, radnetloc, rainloc, rainheat, runoffloc, seepage,        &
       total, windloc
real*8, parameter :: r0 = 0.0d0, r1000=1.0d3, r86400=86400.0d0

integer :: nvarsievap
character*72 :: tec_variables(14)
character*2048 :: strbuffer

nvarsievap = 14

if (isinitial) then
  if (b_output_binary) then    
    call binary_file_open(PETSC_COMM_SELF,         &
                 ievap, prefix(:l_prfx)//'.evap', .true.)
  else    
    open(ievap,file=prefix(:l_prfx)//'.evap',              &
         status='unknown',form='formatted')
  end if
!c  version information
  if (b_writeversion_tecplot .and. .not. b_output_binary) then
      call writeversion2file(ievap, "#")
  end if
        
  if (b_output_binary) then    
    tec_variables(1:nvarsievap) = [character(len=72) :: "time", & 
                                   "ev [kg s-1 m-2]", &
                                   "temp [oC] ", &
                                   "hr [-]", &
                                   "wind [m s-1]", &
                                   "rain [kg s-1 m-2]", &
                                   "runoff [kg s-1 m-2]", &
                                   "rain - runoff [kg s-1 m-2]", &
                                   "rho_v [kg m-3]", &
                                   "pv [Pa]", &
                                   "rad [J s-1 m-2]", &
                                   "lw*ev [J s-1 m-2]", &
                                   "hs [J s-1 m-2]", &
                                   "total [J s-1 m-2]"]
    strbuffer = "temporal evolution about energy "//&
                "and evaporation parameters"
    
    offset_ievap = 0  
    call tecplot_binary_write_header(PETSC_COMM_SELF,          &
                 ievap, "#!TDV102",'dataset '//                &
                 prefix(:l_prfx),offset_ievap,.true.,.true.)                                       
                                                               
    call tecplot_binary_write_variable(PETSC_COMM_SELF,        &
                 ievap, nvarsievap,tec_variables(1:nvarsievap),&
                 offset_ievap,.true.,.true.)                 
                                                               
    call tecplot_binary_write_zoneinfo(PETSC_COMM_SELF,ievap,  &
                 trim(strbuffer),offset_ievap, 1, 1, 1, .true.,&
                 .true.,b_output_multizone)                                
    offset_ievap_ijk = offset_ievap - 5*4            
                                                               
    call tecplot_binary_write_section(PETSC_COMM_SELF,ievap,   &
                 nvarsievap,0,offset_ievap, .true., .true.,    &
                 b_output_multizone) 
  else
    write(ievap,'(3a)') 'title = "dataset ',prefix(:l_prfx),'"'
    write(ievap,'(40a)') 'variables = "time",', & 
                                    ' "ev [kg s-1 m-2]",', &
                                    ' "temp [oC] ",', &
                                    ' "hr [-]",', &
                                    ' "wind [m s-1]",', &
                                    ' "rain [kg s-1 m-2]",', &
                                    ' "runoff [kg s-1 m-2]",', &
                                    ' "rain - runoff [kg s-1 m-2]",', &
                                    ' "rho_v [kg m-3]",', &
                                    ' "pv [Pa]",', &
                                    ' "rad [J s-1 m-2]",', &
                                    ' "lw*ev [J s-1 m-2]",', &
                                    ' "hs [J s-1 m-2]",', &
                                    ' "total [J s-1 m-2]"'
    write(ievap,'(2a)') 'zone t = "temporal evolution about energy ', &
                       'and evaporation parameters", f=point'
  end if
                                 

else
  evaploc = evap_atm/r86400
  levaploc = latvap_atm*evap_atm*r1000/r86400
  hsloc = sheat_atm*r1000/r86400
  radnetloc = radnet*r1000/r86400
  windloc = wind_atm/r86400 
  rainloc = rain_atm*ref_dens/r86400
  runoffloc = runoff_atm/r86400
  seepage = rainloc + runoffloc 
  rainheat = rainloc*heatcapw*temp_atm
  !cprovi------------------------------------------------------------------------------------
  !cprovi Compute the total energy
  !cprovi------------------------------------------------------------------------------------
  total = radnetloc + levaploc + hsloc + rainheat  
  !cprovi------------------------------------------------------------------------------------
  !cprovi Compute the vapour pressure
  !cprovi------------------------------------------------------------------------------------
  call vapor_prop (dummy1,pvloc,dummy2,dummy3,dummy4,temp_atm,r0,r0,hr_atm,ref_dens,1) 
  
  if (b_output_binary) then
    realbuffer_gb(1:nvarsievap) = (/                                   &
               time_io,evaploc,temp_atm,hr_atm,windloc,rainloc,        &
               runoffloc,seepage,densv_atm,pvloc,radnetloc,levaploc,   &
               hsloc,total/)
    call binary_write_data(ievap, 1,(/ngb_tstep/),             &
                                   offset_ievap_ijk,.true.)
    call binary_write_data(ievap, nvarsievap,realbuffer_gb,    &
                                   offset_ievap,.true.) 

    offset_ievap = offset_ievap + nvarsievap*nfloatbit
   
  else
    write(ievap,'(14e15.7)') time_io,evaploc,temp_atm,hr_atm,windloc,rainloc, &
                             runoffloc,seepage,densv_atm,pvloc,radnetloc,levaploc, &
                             hsloc,total  
  end if     

end if

return
end subroutine 
