!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 3 $
!> $Author: dsu $
!> $Date: 2012-12-10 03:46:07 +0100 (Mon, 10 Dec 2012) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/fgerard_new/src/min3p/w_ovendry.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c real*8 function w_ovendry(h,hentry,alpha,n)
!c ------------------------
!c ----------------------------------------------------------------------
real*8 function w_ovendry(h,hentry,alpha,n) 
      
      
implicit none 
      
real*8, intent(in)    :: h
      
real*8, intent(in)    :: n

real*8, intent(in)    :: alpha

real*8, intent(in)    :: hentry

real*8                :: term1     

real*8, parameter     :: r1=1.0d0

term1 = dabs(alpha*(h - hentry))
w_ovendry = r1 / (r1 + term1**n)


 
return
end