/*
     -----------------------------------------------------------

     Code generated by CRA.ModelLayer.ACC - API Code Generator
     http://components.biomamodelling.org/components/acc/help/ 

     MyName MyLastname
     myemail@mydomain.com
     MyInstitution
     14/12/2016 4:40:02 PM

     -----------------------------------------------------------
*/

using System;
using CRA.ModelLayer.Strategy;


namespace SiriusQualityMaizeLAI
{
    /// <summary>
    /// SiriusQualityMaizeLAI component model interface   
    /// </summary>
    public interface IStrategySiriusQualityMaizeLAI : IStrategy
    {
        /// <summary>
        /// Calculate method for models
        /// </summary>
        /// <param name=m>MaizeLAIState Domain class contains the accessors to values</param>
        void Estimate
        ( MaizeLAIState m);
        
        /// <summary>
        /// Test of pre conditions
        /// </summary>
        /// <param name=m>MaizeLAIState Domain class contains the accessors to values</param>
        /// <param name=callID>Preconditions test context</param>
        /// <returns>List of violations</returns>
        string TestPreConditions( MaizeLAIState m, string callID);
        
        /// <summary>
        /// Test of post-conditions
        /// </summary>
        /// <param name=m>MaizeLAIState Domain class contains the accessors to values</param>
        /// <param name=callID>Postconditions test context</param>
        /// <returns>List of violations</returns>
        string TestPostConditions( MaizeLAIState m, string callID);
    
        /// <summary>
        /// Set parameters to the default value
        /// </summary>
        void SetParametersDefaultValue();
    }
}
